// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/api/api.proto
// Protobuf Java Version: 4.29.1

package com.github.iotexproject.grpc.api;

/**
 * Protobuf type {@code iotexapi.GetLogsRequest}
 */
public final class GetLogsRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:iotexapi.GetLogsRequest)
    GetLogsRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      GetLogsRequest.class.getName());
  }
  // Use GetLogsRequest.newBuilder() to construct.
  private GetLogsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetLogsRequest() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.iotexproject.grpc.api.Api.internal_static_iotexapi_GetLogsRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.iotexproject.grpc.api.Api.internal_static_iotexapi_GetLogsRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.iotexproject.grpc.api.GetLogsRequest.class, com.github.iotexproject.grpc.api.GetLogsRequest.Builder.class);
  }

  private int bitField0_;
  private int lookupCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object lookup_;
  public enum LookupCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    BYBLOCK(2),
    BYRANGE(3),
    LOOKUP_NOT_SET(0);
    private final int value;
    private LookupCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static LookupCase valueOf(int value) {
      return forNumber(value);
    }

    public static LookupCase forNumber(int value) {
      switch (value) {
        case 2: return BYBLOCK;
        case 3: return BYRANGE;
        case 0: return LOOKUP_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public LookupCase
  getLookupCase() {
    return LookupCase.forNumber(
        lookupCase_);
  }

  public static final int FILTER_FIELD_NUMBER = 1;
  private com.github.iotexproject.grpc.api.LogsFilter filter_;
  /**
   * <code>.iotexapi.LogsFilter filter = 1;</code>
   * @return Whether the filter field is set.
   */
  @java.lang.Override
  public boolean hasFilter() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.iotexapi.LogsFilter filter = 1;</code>
   * @return The filter.
   */
  @java.lang.Override
  public com.github.iotexproject.grpc.api.LogsFilter getFilter() {
    return filter_ == null ? com.github.iotexproject.grpc.api.LogsFilter.getDefaultInstance() : filter_;
  }
  /**
   * <code>.iotexapi.LogsFilter filter = 1;</code>
   */
  @java.lang.Override
  public com.github.iotexproject.grpc.api.LogsFilterOrBuilder getFilterOrBuilder() {
    return filter_ == null ? com.github.iotexproject.grpc.api.LogsFilter.getDefaultInstance() : filter_;
  }

  public static final int BYBLOCK_FIELD_NUMBER = 2;
  /**
   * <code>.iotexapi.GetLogsByBlock byBlock = 2;</code>
   * @return Whether the byBlock field is set.
   */
  @java.lang.Override
  public boolean hasByBlock() {
    return lookupCase_ == 2;
  }
  /**
   * <code>.iotexapi.GetLogsByBlock byBlock = 2;</code>
   * @return The byBlock.
   */
  @java.lang.Override
  public com.github.iotexproject.grpc.api.GetLogsByBlock getByBlock() {
    if (lookupCase_ == 2) {
       return (com.github.iotexproject.grpc.api.GetLogsByBlock) lookup_;
    }
    return com.github.iotexproject.grpc.api.GetLogsByBlock.getDefaultInstance();
  }
  /**
   * <code>.iotexapi.GetLogsByBlock byBlock = 2;</code>
   */
  @java.lang.Override
  public com.github.iotexproject.grpc.api.GetLogsByBlockOrBuilder getByBlockOrBuilder() {
    if (lookupCase_ == 2) {
       return (com.github.iotexproject.grpc.api.GetLogsByBlock) lookup_;
    }
    return com.github.iotexproject.grpc.api.GetLogsByBlock.getDefaultInstance();
  }

  public static final int BYRANGE_FIELD_NUMBER = 3;
  /**
   * <code>.iotexapi.GetLogsByRange byRange = 3;</code>
   * @return Whether the byRange field is set.
   */
  @java.lang.Override
  public boolean hasByRange() {
    return lookupCase_ == 3;
  }
  /**
   * <code>.iotexapi.GetLogsByRange byRange = 3;</code>
   * @return The byRange.
   */
  @java.lang.Override
  public com.github.iotexproject.grpc.api.GetLogsByRange getByRange() {
    if (lookupCase_ == 3) {
       return (com.github.iotexproject.grpc.api.GetLogsByRange) lookup_;
    }
    return com.github.iotexproject.grpc.api.GetLogsByRange.getDefaultInstance();
  }
  /**
   * <code>.iotexapi.GetLogsByRange byRange = 3;</code>
   */
  @java.lang.Override
  public com.github.iotexproject.grpc.api.GetLogsByRangeOrBuilder getByRangeOrBuilder() {
    if (lookupCase_ == 3) {
       return (com.github.iotexproject.grpc.api.GetLogsByRange) lookup_;
    }
    return com.github.iotexproject.grpc.api.GetLogsByRange.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getFilter());
    }
    if (lookupCase_ == 2) {
      output.writeMessage(2, (com.github.iotexproject.grpc.api.GetLogsByBlock) lookup_);
    }
    if (lookupCase_ == 3) {
      output.writeMessage(3, (com.github.iotexproject.grpc.api.GetLogsByRange) lookup_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getFilter());
    }
    if (lookupCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.github.iotexproject.grpc.api.GetLogsByBlock) lookup_);
    }
    if (lookupCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.github.iotexproject.grpc.api.GetLogsByRange) lookup_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.iotexproject.grpc.api.GetLogsRequest)) {
      return super.equals(obj);
    }
    com.github.iotexproject.grpc.api.GetLogsRequest other = (com.github.iotexproject.grpc.api.GetLogsRequest) obj;

    if (hasFilter() != other.hasFilter()) return false;
    if (hasFilter()) {
      if (!getFilter()
          .equals(other.getFilter())) return false;
    }
    if (!getLookupCase().equals(other.getLookupCase())) return false;
    switch (lookupCase_) {
      case 2:
        if (!getByBlock()
            .equals(other.getByBlock())) return false;
        break;
      case 3:
        if (!getByRange()
            .equals(other.getByRange())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasFilter()) {
      hash = (37 * hash) + FILTER_FIELD_NUMBER;
      hash = (53 * hash) + getFilter().hashCode();
    }
    switch (lookupCase_) {
      case 2:
        hash = (37 * hash) + BYBLOCK_FIELD_NUMBER;
        hash = (53 * hash) + getByBlock().hashCode();
        break;
      case 3:
        hash = (37 * hash) + BYRANGE_FIELD_NUMBER;
        hash = (53 * hash) + getByRange().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.iotexproject.grpc.api.GetLogsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.api.GetLogsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.api.GetLogsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.api.GetLogsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.api.GetLogsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.api.GetLogsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.api.GetLogsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.api.GetLogsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.iotexproject.grpc.api.GetLogsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.iotexproject.grpc.api.GetLogsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.api.GetLogsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.api.GetLogsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.iotexproject.grpc.api.GetLogsRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code iotexapi.GetLogsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:iotexapi.GetLogsRequest)
      com.github.iotexproject.grpc.api.GetLogsRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.iotexproject.grpc.api.Api.internal_static_iotexapi_GetLogsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.iotexproject.grpc.api.Api.internal_static_iotexapi_GetLogsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.iotexproject.grpc.api.GetLogsRequest.class, com.github.iotexproject.grpc.api.GetLogsRequest.Builder.class);
    }

    // Construct using com.github.iotexproject.grpc.api.GetLogsRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getFilterFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      filter_ = null;
      if (filterBuilder_ != null) {
        filterBuilder_.dispose();
        filterBuilder_ = null;
      }
      if (byBlockBuilder_ != null) {
        byBlockBuilder_.clear();
      }
      if (byRangeBuilder_ != null) {
        byRangeBuilder_.clear();
      }
      lookupCase_ = 0;
      lookup_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.iotexproject.grpc.api.Api.internal_static_iotexapi_GetLogsRequest_descriptor;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.api.GetLogsRequest getDefaultInstanceForType() {
      return com.github.iotexproject.grpc.api.GetLogsRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.api.GetLogsRequest build() {
      com.github.iotexproject.grpc.api.GetLogsRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.api.GetLogsRequest buildPartial() {
      com.github.iotexproject.grpc.api.GetLogsRequest result = new com.github.iotexproject.grpc.api.GetLogsRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.github.iotexproject.grpc.api.GetLogsRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.filter_ = filterBuilder_ == null
            ? filter_
            : filterBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    private void buildPartialOneofs(com.github.iotexproject.grpc.api.GetLogsRequest result) {
      result.lookupCase_ = lookupCase_;
      result.lookup_ = this.lookup_;
      if (lookupCase_ == 2 &&
          byBlockBuilder_ != null) {
        result.lookup_ = byBlockBuilder_.build();
      }
      if (lookupCase_ == 3 &&
          byRangeBuilder_ != null) {
        result.lookup_ = byRangeBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.iotexproject.grpc.api.GetLogsRequest) {
        return mergeFrom((com.github.iotexproject.grpc.api.GetLogsRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.iotexproject.grpc.api.GetLogsRequest other) {
      if (other == com.github.iotexproject.grpc.api.GetLogsRequest.getDefaultInstance()) return this;
      if (other.hasFilter()) {
        mergeFilter(other.getFilter());
      }
      switch (other.getLookupCase()) {
        case BYBLOCK: {
          mergeByBlock(other.getByBlock());
          break;
        }
        case BYRANGE: {
          mergeByRange(other.getByRange());
          break;
        }
        case LOOKUP_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getFilterFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getByBlockFieldBuilder().getBuilder(),
                  extensionRegistry);
              lookupCase_ = 2;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getByRangeFieldBuilder().getBuilder(),
                  extensionRegistry);
              lookupCase_ = 3;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int lookupCase_ = 0;
    private java.lang.Object lookup_;
    public LookupCase
        getLookupCase() {
      return LookupCase.forNumber(
          lookupCase_);
    }

    public Builder clearLookup() {
      lookupCase_ = 0;
      lookup_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private com.github.iotexproject.grpc.api.LogsFilter filter_;
    private com.google.protobuf.SingleFieldBuilder<
        com.github.iotexproject.grpc.api.LogsFilter, com.github.iotexproject.grpc.api.LogsFilter.Builder, com.github.iotexproject.grpc.api.LogsFilterOrBuilder> filterBuilder_;
    /**
     * <code>.iotexapi.LogsFilter filter = 1;</code>
     * @return Whether the filter field is set.
     */
    public boolean hasFilter() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.iotexapi.LogsFilter filter = 1;</code>
     * @return The filter.
     */
    public com.github.iotexproject.grpc.api.LogsFilter getFilter() {
      if (filterBuilder_ == null) {
        return filter_ == null ? com.github.iotexproject.grpc.api.LogsFilter.getDefaultInstance() : filter_;
      } else {
        return filterBuilder_.getMessage();
      }
    }
    /**
     * <code>.iotexapi.LogsFilter filter = 1;</code>
     */
    public Builder setFilter(com.github.iotexproject.grpc.api.LogsFilter value) {
      if (filterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        filter_ = value;
      } else {
        filterBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.iotexapi.LogsFilter filter = 1;</code>
     */
    public Builder setFilter(
        com.github.iotexproject.grpc.api.LogsFilter.Builder builderForValue) {
      if (filterBuilder_ == null) {
        filter_ = builderForValue.build();
      } else {
        filterBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.iotexapi.LogsFilter filter = 1;</code>
     */
    public Builder mergeFilter(com.github.iotexproject.grpc.api.LogsFilter value) {
      if (filterBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          filter_ != null &&
          filter_ != com.github.iotexproject.grpc.api.LogsFilter.getDefaultInstance()) {
          getFilterBuilder().mergeFrom(value);
        } else {
          filter_ = value;
        }
      } else {
        filterBuilder_.mergeFrom(value);
      }
      if (filter_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.iotexapi.LogsFilter filter = 1;</code>
     */
    public Builder clearFilter() {
      bitField0_ = (bitField0_ & ~0x00000001);
      filter_ = null;
      if (filterBuilder_ != null) {
        filterBuilder_.dispose();
        filterBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.iotexapi.LogsFilter filter = 1;</code>
     */
    public com.github.iotexproject.grpc.api.LogsFilter.Builder getFilterBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getFilterFieldBuilder().getBuilder();
    }
    /**
     * <code>.iotexapi.LogsFilter filter = 1;</code>
     */
    public com.github.iotexproject.grpc.api.LogsFilterOrBuilder getFilterOrBuilder() {
      if (filterBuilder_ != null) {
        return filterBuilder_.getMessageOrBuilder();
      } else {
        return filter_ == null ?
            com.github.iotexproject.grpc.api.LogsFilter.getDefaultInstance() : filter_;
      }
    }
    /**
     * <code>.iotexapi.LogsFilter filter = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.iotexproject.grpc.api.LogsFilter, com.github.iotexproject.grpc.api.LogsFilter.Builder, com.github.iotexproject.grpc.api.LogsFilterOrBuilder> 
        getFilterFieldBuilder() {
      if (filterBuilder_ == null) {
        filterBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.iotexproject.grpc.api.LogsFilter, com.github.iotexproject.grpc.api.LogsFilter.Builder, com.github.iotexproject.grpc.api.LogsFilterOrBuilder>(
                getFilter(),
                getParentForChildren(),
                isClean());
        filter_ = null;
      }
      return filterBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.github.iotexproject.grpc.api.GetLogsByBlock, com.github.iotexproject.grpc.api.GetLogsByBlock.Builder, com.github.iotexproject.grpc.api.GetLogsByBlockOrBuilder> byBlockBuilder_;
    /**
     * <code>.iotexapi.GetLogsByBlock byBlock = 2;</code>
     * @return Whether the byBlock field is set.
     */
    @java.lang.Override
    public boolean hasByBlock() {
      return lookupCase_ == 2;
    }
    /**
     * <code>.iotexapi.GetLogsByBlock byBlock = 2;</code>
     * @return The byBlock.
     */
    @java.lang.Override
    public com.github.iotexproject.grpc.api.GetLogsByBlock getByBlock() {
      if (byBlockBuilder_ == null) {
        if (lookupCase_ == 2) {
          return (com.github.iotexproject.grpc.api.GetLogsByBlock) lookup_;
        }
        return com.github.iotexproject.grpc.api.GetLogsByBlock.getDefaultInstance();
      } else {
        if (lookupCase_ == 2) {
          return byBlockBuilder_.getMessage();
        }
        return com.github.iotexproject.grpc.api.GetLogsByBlock.getDefaultInstance();
      }
    }
    /**
     * <code>.iotexapi.GetLogsByBlock byBlock = 2;</code>
     */
    public Builder setByBlock(com.github.iotexproject.grpc.api.GetLogsByBlock value) {
      if (byBlockBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lookup_ = value;
        onChanged();
      } else {
        byBlockBuilder_.setMessage(value);
      }
      lookupCase_ = 2;
      return this;
    }
    /**
     * <code>.iotexapi.GetLogsByBlock byBlock = 2;</code>
     */
    public Builder setByBlock(
        com.github.iotexproject.grpc.api.GetLogsByBlock.Builder builderForValue) {
      if (byBlockBuilder_ == null) {
        lookup_ = builderForValue.build();
        onChanged();
      } else {
        byBlockBuilder_.setMessage(builderForValue.build());
      }
      lookupCase_ = 2;
      return this;
    }
    /**
     * <code>.iotexapi.GetLogsByBlock byBlock = 2;</code>
     */
    public Builder mergeByBlock(com.github.iotexproject.grpc.api.GetLogsByBlock value) {
      if (byBlockBuilder_ == null) {
        if (lookupCase_ == 2 &&
            lookup_ != com.github.iotexproject.grpc.api.GetLogsByBlock.getDefaultInstance()) {
          lookup_ = com.github.iotexproject.grpc.api.GetLogsByBlock.newBuilder((com.github.iotexproject.grpc.api.GetLogsByBlock) lookup_)
              .mergeFrom(value).buildPartial();
        } else {
          lookup_ = value;
        }
        onChanged();
      } else {
        if (lookupCase_ == 2) {
          byBlockBuilder_.mergeFrom(value);
        } else {
          byBlockBuilder_.setMessage(value);
        }
      }
      lookupCase_ = 2;
      return this;
    }
    /**
     * <code>.iotexapi.GetLogsByBlock byBlock = 2;</code>
     */
    public Builder clearByBlock() {
      if (byBlockBuilder_ == null) {
        if (lookupCase_ == 2) {
          lookupCase_ = 0;
          lookup_ = null;
          onChanged();
        }
      } else {
        if (lookupCase_ == 2) {
          lookupCase_ = 0;
          lookup_ = null;
        }
        byBlockBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.iotexapi.GetLogsByBlock byBlock = 2;</code>
     */
    public com.github.iotexproject.grpc.api.GetLogsByBlock.Builder getByBlockBuilder() {
      return getByBlockFieldBuilder().getBuilder();
    }
    /**
     * <code>.iotexapi.GetLogsByBlock byBlock = 2;</code>
     */
    @java.lang.Override
    public com.github.iotexproject.grpc.api.GetLogsByBlockOrBuilder getByBlockOrBuilder() {
      if ((lookupCase_ == 2) && (byBlockBuilder_ != null)) {
        return byBlockBuilder_.getMessageOrBuilder();
      } else {
        if (lookupCase_ == 2) {
          return (com.github.iotexproject.grpc.api.GetLogsByBlock) lookup_;
        }
        return com.github.iotexproject.grpc.api.GetLogsByBlock.getDefaultInstance();
      }
    }
    /**
     * <code>.iotexapi.GetLogsByBlock byBlock = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.iotexproject.grpc.api.GetLogsByBlock, com.github.iotexproject.grpc.api.GetLogsByBlock.Builder, com.github.iotexproject.grpc.api.GetLogsByBlockOrBuilder> 
        getByBlockFieldBuilder() {
      if (byBlockBuilder_ == null) {
        if (!(lookupCase_ == 2)) {
          lookup_ = com.github.iotexproject.grpc.api.GetLogsByBlock.getDefaultInstance();
        }
        byBlockBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.iotexproject.grpc.api.GetLogsByBlock, com.github.iotexproject.grpc.api.GetLogsByBlock.Builder, com.github.iotexproject.grpc.api.GetLogsByBlockOrBuilder>(
                (com.github.iotexproject.grpc.api.GetLogsByBlock) lookup_,
                getParentForChildren(),
                isClean());
        lookup_ = null;
      }
      lookupCase_ = 2;
      onChanged();
      return byBlockBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.github.iotexproject.grpc.api.GetLogsByRange, com.github.iotexproject.grpc.api.GetLogsByRange.Builder, com.github.iotexproject.grpc.api.GetLogsByRangeOrBuilder> byRangeBuilder_;
    /**
     * <code>.iotexapi.GetLogsByRange byRange = 3;</code>
     * @return Whether the byRange field is set.
     */
    @java.lang.Override
    public boolean hasByRange() {
      return lookupCase_ == 3;
    }
    /**
     * <code>.iotexapi.GetLogsByRange byRange = 3;</code>
     * @return The byRange.
     */
    @java.lang.Override
    public com.github.iotexproject.grpc.api.GetLogsByRange getByRange() {
      if (byRangeBuilder_ == null) {
        if (lookupCase_ == 3) {
          return (com.github.iotexproject.grpc.api.GetLogsByRange) lookup_;
        }
        return com.github.iotexproject.grpc.api.GetLogsByRange.getDefaultInstance();
      } else {
        if (lookupCase_ == 3) {
          return byRangeBuilder_.getMessage();
        }
        return com.github.iotexproject.grpc.api.GetLogsByRange.getDefaultInstance();
      }
    }
    /**
     * <code>.iotexapi.GetLogsByRange byRange = 3;</code>
     */
    public Builder setByRange(com.github.iotexproject.grpc.api.GetLogsByRange value) {
      if (byRangeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lookup_ = value;
        onChanged();
      } else {
        byRangeBuilder_.setMessage(value);
      }
      lookupCase_ = 3;
      return this;
    }
    /**
     * <code>.iotexapi.GetLogsByRange byRange = 3;</code>
     */
    public Builder setByRange(
        com.github.iotexproject.grpc.api.GetLogsByRange.Builder builderForValue) {
      if (byRangeBuilder_ == null) {
        lookup_ = builderForValue.build();
        onChanged();
      } else {
        byRangeBuilder_.setMessage(builderForValue.build());
      }
      lookupCase_ = 3;
      return this;
    }
    /**
     * <code>.iotexapi.GetLogsByRange byRange = 3;</code>
     */
    public Builder mergeByRange(com.github.iotexproject.grpc.api.GetLogsByRange value) {
      if (byRangeBuilder_ == null) {
        if (lookupCase_ == 3 &&
            lookup_ != com.github.iotexproject.grpc.api.GetLogsByRange.getDefaultInstance()) {
          lookup_ = com.github.iotexproject.grpc.api.GetLogsByRange.newBuilder((com.github.iotexproject.grpc.api.GetLogsByRange) lookup_)
              .mergeFrom(value).buildPartial();
        } else {
          lookup_ = value;
        }
        onChanged();
      } else {
        if (lookupCase_ == 3) {
          byRangeBuilder_.mergeFrom(value);
        } else {
          byRangeBuilder_.setMessage(value);
        }
      }
      lookupCase_ = 3;
      return this;
    }
    /**
     * <code>.iotexapi.GetLogsByRange byRange = 3;</code>
     */
    public Builder clearByRange() {
      if (byRangeBuilder_ == null) {
        if (lookupCase_ == 3) {
          lookupCase_ = 0;
          lookup_ = null;
          onChanged();
        }
      } else {
        if (lookupCase_ == 3) {
          lookupCase_ = 0;
          lookup_ = null;
        }
        byRangeBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.iotexapi.GetLogsByRange byRange = 3;</code>
     */
    public com.github.iotexproject.grpc.api.GetLogsByRange.Builder getByRangeBuilder() {
      return getByRangeFieldBuilder().getBuilder();
    }
    /**
     * <code>.iotexapi.GetLogsByRange byRange = 3;</code>
     */
    @java.lang.Override
    public com.github.iotexproject.grpc.api.GetLogsByRangeOrBuilder getByRangeOrBuilder() {
      if ((lookupCase_ == 3) && (byRangeBuilder_ != null)) {
        return byRangeBuilder_.getMessageOrBuilder();
      } else {
        if (lookupCase_ == 3) {
          return (com.github.iotexproject.grpc.api.GetLogsByRange) lookup_;
        }
        return com.github.iotexproject.grpc.api.GetLogsByRange.getDefaultInstance();
      }
    }
    /**
     * <code>.iotexapi.GetLogsByRange byRange = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.iotexproject.grpc.api.GetLogsByRange, com.github.iotexproject.grpc.api.GetLogsByRange.Builder, com.github.iotexproject.grpc.api.GetLogsByRangeOrBuilder> 
        getByRangeFieldBuilder() {
      if (byRangeBuilder_ == null) {
        if (!(lookupCase_ == 3)) {
          lookup_ = com.github.iotexproject.grpc.api.GetLogsByRange.getDefaultInstance();
        }
        byRangeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.iotexproject.grpc.api.GetLogsByRange, com.github.iotexproject.grpc.api.GetLogsByRange.Builder, com.github.iotexproject.grpc.api.GetLogsByRangeOrBuilder>(
                (com.github.iotexproject.grpc.api.GetLogsByRange) lookup_,
                getParentForChildren(),
                isClean());
        lookup_ = null;
      }
      lookupCase_ = 3;
      onChanged();
      return byRangeBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:iotexapi.GetLogsRequest)
  }

  // @@protoc_insertion_point(class_scope:iotexapi.GetLogsRequest)
  private static final com.github.iotexproject.grpc.api.GetLogsRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.iotexproject.grpc.api.GetLogsRequest();
  }

  public static com.github.iotexproject.grpc.api.GetLogsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetLogsRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetLogsRequest>() {
    @java.lang.Override
    public GetLogsRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetLogsRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetLogsRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.iotexproject.grpc.api.GetLogsRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

