// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/api/api.proto
// Protobuf Java Version: 4.29.1

package com.github.iotexproject.grpc.api;

/**
 * Protobuf type {@code iotexapi.GetReceiptByActionResponse}
 */
public final class GetReceiptByActionResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:iotexapi.GetReceiptByActionResponse)
    GetReceiptByActionResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      GetReceiptByActionResponse.class.getName());
  }
  // Use GetReceiptByActionResponse.newBuilder() to construct.
  private GetReceiptByActionResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetReceiptByActionResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.iotexproject.grpc.api.Api.internal_static_iotexapi_GetReceiptByActionResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.iotexproject.grpc.api.Api.internal_static_iotexapi_GetReceiptByActionResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.iotexproject.grpc.api.GetReceiptByActionResponse.class, com.github.iotexproject.grpc.api.GetReceiptByActionResponse.Builder.class);
  }

  private int bitField0_;
  public static final int RECEIPTINFO_FIELD_NUMBER = 1;
  private com.github.iotexproject.grpc.api.ReceiptInfo receiptInfo_;
  /**
   * <code>.iotexapi.ReceiptInfo receiptInfo = 1;</code>
   * @return Whether the receiptInfo field is set.
   */
  @java.lang.Override
  public boolean hasReceiptInfo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.iotexapi.ReceiptInfo receiptInfo = 1;</code>
   * @return The receiptInfo.
   */
  @java.lang.Override
  public com.github.iotexproject.grpc.api.ReceiptInfo getReceiptInfo() {
    return receiptInfo_ == null ? com.github.iotexproject.grpc.api.ReceiptInfo.getDefaultInstance() : receiptInfo_;
  }
  /**
   * <code>.iotexapi.ReceiptInfo receiptInfo = 1;</code>
   */
  @java.lang.Override
  public com.github.iotexproject.grpc.api.ReceiptInfoOrBuilder getReceiptInfoOrBuilder() {
    return receiptInfo_ == null ? com.github.iotexproject.grpc.api.ReceiptInfo.getDefaultInstance() : receiptInfo_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getReceiptInfo());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getReceiptInfo());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.iotexproject.grpc.api.GetReceiptByActionResponse)) {
      return super.equals(obj);
    }
    com.github.iotexproject.grpc.api.GetReceiptByActionResponse other = (com.github.iotexproject.grpc.api.GetReceiptByActionResponse) obj;

    if (hasReceiptInfo() != other.hasReceiptInfo()) return false;
    if (hasReceiptInfo()) {
      if (!getReceiptInfo()
          .equals(other.getReceiptInfo())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasReceiptInfo()) {
      hash = (37 * hash) + RECEIPTINFO_FIELD_NUMBER;
      hash = (53 * hash) + getReceiptInfo().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.iotexproject.grpc.api.GetReceiptByActionResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.api.GetReceiptByActionResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.api.GetReceiptByActionResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.api.GetReceiptByActionResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.api.GetReceiptByActionResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.api.GetReceiptByActionResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.api.GetReceiptByActionResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.api.GetReceiptByActionResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.iotexproject.grpc.api.GetReceiptByActionResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.iotexproject.grpc.api.GetReceiptByActionResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.api.GetReceiptByActionResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.api.GetReceiptByActionResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.iotexproject.grpc.api.GetReceiptByActionResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code iotexapi.GetReceiptByActionResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:iotexapi.GetReceiptByActionResponse)
      com.github.iotexproject.grpc.api.GetReceiptByActionResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.iotexproject.grpc.api.Api.internal_static_iotexapi_GetReceiptByActionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.iotexproject.grpc.api.Api.internal_static_iotexapi_GetReceiptByActionResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.iotexproject.grpc.api.GetReceiptByActionResponse.class, com.github.iotexproject.grpc.api.GetReceiptByActionResponse.Builder.class);
    }

    // Construct using com.github.iotexproject.grpc.api.GetReceiptByActionResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getReceiptInfoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      receiptInfo_ = null;
      if (receiptInfoBuilder_ != null) {
        receiptInfoBuilder_.dispose();
        receiptInfoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.iotexproject.grpc.api.Api.internal_static_iotexapi_GetReceiptByActionResponse_descriptor;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.api.GetReceiptByActionResponse getDefaultInstanceForType() {
      return com.github.iotexproject.grpc.api.GetReceiptByActionResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.api.GetReceiptByActionResponse build() {
      com.github.iotexproject.grpc.api.GetReceiptByActionResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.api.GetReceiptByActionResponse buildPartial() {
      com.github.iotexproject.grpc.api.GetReceiptByActionResponse result = new com.github.iotexproject.grpc.api.GetReceiptByActionResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.github.iotexproject.grpc.api.GetReceiptByActionResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.receiptInfo_ = receiptInfoBuilder_ == null
            ? receiptInfo_
            : receiptInfoBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.iotexproject.grpc.api.GetReceiptByActionResponse) {
        return mergeFrom((com.github.iotexproject.grpc.api.GetReceiptByActionResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.iotexproject.grpc.api.GetReceiptByActionResponse other) {
      if (other == com.github.iotexproject.grpc.api.GetReceiptByActionResponse.getDefaultInstance()) return this;
      if (other.hasReceiptInfo()) {
        mergeReceiptInfo(other.getReceiptInfo());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getReceiptInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.github.iotexproject.grpc.api.ReceiptInfo receiptInfo_;
    private com.google.protobuf.SingleFieldBuilder<
        com.github.iotexproject.grpc.api.ReceiptInfo, com.github.iotexproject.grpc.api.ReceiptInfo.Builder, com.github.iotexproject.grpc.api.ReceiptInfoOrBuilder> receiptInfoBuilder_;
    /**
     * <code>.iotexapi.ReceiptInfo receiptInfo = 1;</code>
     * @return Whether the receiptInfo field is set.
     */
    public boolean hasReceiptInfo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.iotexapi.ReceiptInfo receiptInfo = 1;</code>
     * @return The receiptInfo.
     */
    public com.github.iotexproject.grpc.api.ReceiptInfo getReceiptInfo() {
      if (receiptInfoBuilder_ == null) {
        return receiptInfo_ == null ? com.github.iotexproject.grpc.api.ReceiptInfo.getDefaultInstance() : receiptInfo_;
      } else {
        return receiptInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.iotexapi.ReceiptInfo receiptInfo = 1;</code>
     */
    public Builder setReceiptInfo(com.github.iotexproject.grpc.api.ReceiptInfo value) {
      if (receiptInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        receiptInfo_ = value;
      } else {
        receiptInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.iotexapi.ReceiptInfo receiptInfo = 1;</code>
     */
    public Builder setReceiptInfo(
        com.github.iotexproject.grpc.api.ReceiptInfo.Builder builderForValue) {
      if (receiptInfoBuilder_ == null) {
        receiptInfo_ = builderForValue.build();
      } else {
        receiptInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.iotexapi.ReceiptInfo receiptInfo = 1;</code>
     */
    public Builder mergeReceiptInfo(com.github.iotexproject.grpc.api.ReceiptInfo value) {
      if (receiptInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          receiptInfo_ != null &&
          receiptInfo_ != com.github.iotexproject.grpc.api.ReceiptInfo.getDefaultInstance()) {
          getReceiptInfoBuilder().mergeFrom(value);
        } else {
          receiptInfo_ = value;
        }
      } else {
        receiptInfoBuilder_.mergeFrom(value);
      }
      if (receiptInfo_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.iotexapi.ReceiptInfo receiptInfo = 1;</code>
     */
    public Builder clearReceiptInfo() {
      bitField0_ = (bitField0_ & ~0x00000001);
      receiptInfo_ = null;
      if (receiptInfoBuilder_ != null) {
        receiptInfoBuilder_.dispose();
        receiptInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.iotexapi.ReceiptInfo receiptInfo = 1;</code>
     */
    public com.github.iotexproject.grpc.api.ReceiptInfo.Builder getReceiptInfoBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getReceiptInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.iotexapi.ReceiptInfo receiptInfo = 1;</code>
     */
    public com.github.iotexproject.grpc.api.ReceiptInfoOrBuilder getReceiptInfoOrBuilder() {
      if (receiptInfoBuilder_ != null) {
        return receiptInfoBuilder_.getMessageOrBuilder();
      } else {
        return receiptInfo_ == null ?
            com.github.iotexproject.grpc.api.ReceiptInfo.getDefaultInstance() : receiptInfo_;
      }
    }
    /**
     * <code>.iotexapi.ReceiptInfo receiptInfo = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.iotexproject.grpc.api.ReceiptInfo, com.github.iotexproject.grpc.api.ReceiptInfo.Builder, com.github.iotexproject.grpc.api.ReceiptInfoOrBuilder> 
        getReceiptInfoFieldBuilder() {
      if (receiptInfoBuilder_ == null) {
        receiptInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.iotexproject.grpc.api.ReceiptInfo, com.github.iotexproject.grpc.api.ReceiptInfo.Builder, com.github.iotexproject.grpc.api.ReceiptInfoOrBuilder>(
                getReceiptInfo(),
                getParentForChildren(),
                isClean());
        receiptInfo_ = null;
      }
      return receiptInfoBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:iotexapi.GetReceiptByActionResponse)
  }

  // @@protoc_insertion_point(class_scope:iotexapi.GetReceiptByActionResponse)
  private static final com.github.iotexproject.grpc.api.GetReceiptByActionResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.iotexproject.grpc.api.GetReceiptByActionResponse();
  }

  public static com.github.iotexproject.grpc.api.GetReceiptByActionResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetReceiptByActionResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetReceiptByActionResponse>() {
    @java.lang.Override
    public GetReceiptByActionResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetReceiptByActionResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetReceiptByActionResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.iotexproject.grpc.api.GetReceiptByActionResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

