// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/api/api.proto
// Protobuf Java Version: 4.29.1

package com.github.iotexproject.grpc.api;

public interface SendSignedActionBytesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:iotexapi.SendSignedActionBytesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string signedActionBytes = 1;</code>
   * @return The signedActionBytes.
   */
  java.lang.String getSignedActionBytes();
  /**
   * <code>string signedActionBytes = 1;</code>
   * @return The bytes for signedActionBytes.
   */
  com.google.protobuf.ByteString
      getSignedActionBytesBytes();
}
