// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/api/api.proto
// Protobuf Java Version: 4.34.1

package com.github.iotexproject.grpc.api;

@com.google.protobuf.Generated
public interface SuggestGasPriceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:iotexapi.SuggestGasPriceRequest)
    com.google.protobuf.MessageOrBuilder {
}
