// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/rpc/rpc.proto
// Protobuf Java Version: 4.29.1

package com.github.iotexproject.grpc.rpc;

/**
 * Protobuf type {@code iotexrpc.ActionSync}
 */
public final class ActionSync extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:iotexrpc.ActionSync)
    ActionSyncOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      ActionSync.class.getName());
  }
  // Use ActionSync.newBuilder() to construct.
  private ActionSync(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ActionSync() {
    hashes_ = emptyList(com.google.protobuf.ByteString.class);
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.iotexproject.grpc.rpc.Rpc.internal_static_iotexrpc_ActionSync_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.iotexproject.grpc.rpc.Rpc.internal_static_iotexrpc_ActionSync_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.iotexproject.grpc.rpc.ActionSync.class, com.github.iotexproject.grpc.rpc.ActionSync.Builder.class);
  }

  public static final int HASHES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> hashes_ =
      emptyList(com.google.protobuf.ByteString.class);
  /**
   * <code>repeated bytes hashes = 1;</code>
   * @return A list containing the hashes.
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.ByteString>
      getHashesList() {
    return hashes_;
  }
  /**
   * <code>repeated bytes hashes = 1;</code>
   * @return The count of hashes.
   */
  public int getHashesCount() {
    return hashes_.size();
  }
  /**
   * <code>repeated bytes hashes = 1;</code>
   * @param index The index of the element to return.
   * @return The hashes at the given index.
   */
  public com.google.protobuf.ByteString getHashes(int index) {
    return hashes_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < hashes_.size(); i++) {
      output.writeBytes(1, hashes_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < hashes_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(hashes_.get(i));
      }
      size += dataSize;
      size += 1 * getHashesList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.iotexproject.grpc.rpc.ActionSync)) {
      return super.equals(obj);
    }
    com.github.iotexproject.grpc.rpc.ActionSync other = (com.github.iotexproject.grpc.rpc.ActionSync) obj;

    if (!getHashesList()
        .equals(other.getHashesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getHashesCount() > 0) {
      hash = (37 * hash) + HASHES_FIELD_NUMBER;
      hash = (53 * hash) + getHashesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.iotexproject.grpc.rpc.ActionSync parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.rpc.ActionSync parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.rpc.ActionSync parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.rpc.ActionSync parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.rpc.ActionSync parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.rpc.ActionSync parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.rpc.ActionSync parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.rpc.ActionSync parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.iotexproject.grpc.rpc.ActionSync parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.iotexproject.grpc.rpc.ActionSync parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.rpc.ActionSync parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.rpc.ActionSync parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.iotexproject.grpc.rpc.ActionSync prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code iotexrpc.ActionSync}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:iotexrpc.ActionSync)
      com.github.iotexproject.grpc.rpc.ActionSyncOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.iotexproject.grpc.rpc.Rpc.internal_static_iotexrpc_ActionSync_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.iotexproject.grpc.rpc.Rpc.internal_static_iotexrpc_ActionSync_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.iotexproject.grpc.rpc.ActionSync.class, com.github.iotexproject.grpc.rpc.ActionSync.Builder.class);
    }

    // Construct using com.github.iotexproject.grpc.rpc.ActionSync.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      hashes_ = emptyList(com.google.protobuf.ByteString.class);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.iotexproject.grpc.rpc.Rpc.internal_static_iotexrpc_ActionSync_descriptor;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.rpc.ActionSync getDefaultInstanceForType() {
      return com.github.iotexproject.grpc.rpc.ActionSync.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.rpc.ActionSync build() {
      com.github.iotexproject.grpc.rpc.ActionSync result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.rpc.ActionSync buildPartial() {
      com.github.iotexproject.grpc.rpc.ActionSync result = new com.github.iotexproject.grpc.rpc.ActionSync(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.github.iotexproject.grpc.rpc.ActionSync result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        hashes_.makeImmutable();
        result.hashes_ = hashes_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.iotexproject.grpc.rpc.ActionSync) {
        return mergeFrom((com.github.iotexproject.grpc.rpc.ActionSync)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.iotexproject.grpc.rpc.ActionSync other) {
      if (other == com.github.iotexproject.grpc.rpc.ActionSync.getDefaultInstance()) return this;
      if (!other.hashes_.isEmpty()) {
        if (hashes_.isEmpty()) {
          hashes_ = other.hashes_;
          hashes_.makeImmutable();
          bitField0_ |= 0x00000001;
        } else {
          ensureHashesIsMutable();
          hashes_.addAll(other.hashes_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString v = input.readBytes();
              ensureHashesIsMutable();
              hashes_.add(v);
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> hashes_ = emptyList(com.google.protobuf.ByteString.class);
    private void ensureHashesIsMutable() {
      if (!hashes_.isModifiable()) {
        hashes_ = makeMutableCopy(hashes_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated bytes hashes = 1;</code>
     * @return A list containing the hashes.
     */
    public java.util.List<com.google.protobuf.ByteString>
        getHashesList() {
      hashes_.makeImmutable();
      return hashes_;
    }
    /**
     * <code>repeated bytes hashes = 1;</code>
     * @return The count of hashes.
     */
    public int getHashesCount() {
      return hashes_.size();
    }
    /**
     * <code>repeated bytes hashes = 1;</code>
     * @param index The index of the element to return.
     * @return The hashes at the given index.
     */
    public com.google.protobuf.ByteString getHashes(int index) {
      return hashes_.get(index);
    }
    /**
     * <code>repeated bytes hashes = 1;</code>
     * @param index The index to set the value at.
     * @param value The hashes to set.
     * @return This builder for chaining.
     */
    public Builder setHashes(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      ensureHashesIsMutable();
      hashes_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes hashes = 1;</code>
     * @param value The hashes to add.
     * @return This builder for chaining.
     */
    public Builder addHashes(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      ensureHashesIsMutable();
      hashes_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes hashes = 1;</code>
     * @param values The hashes to add.
     * @return This builder for chaining.
     */
    public Builder addAllHashes(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureHashesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, hashes_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes hashes = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHashes() {
      hashes_ = emptyList(com.google.protobuf.ByteString.class);
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:iotexrpc.ActionSync)
  }

  // @@protoc_insertion_point(class_scope:iotexrpc.ActionSync)
  private static final com.github.iotexproject.grpc.rpc.ActionSync DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.iotexproject.grpc.rpc.ActionSync();
  }

  public static com.github.iotexproject.grpc.rpc.ActionSync getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ActionSync>
      PARSER = new com.google.protobuf.AbstractParser<ActionSync>() {
    @java.lang.Override
    public ActionSync parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ActionSync> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ActionSync> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.iotexproject.grpc.rpc.ActionSync getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

