// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/rpc/rpc.proto
// Protobuf Java Version: 4.29.1

package com.github.iotexproject.grpc.rpc;

public interface BlockSyncOrBuilder extends
    // @@protoc_insertion_point(interface_extends:iotexrpc.BlockSync)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 start = 2;</code>
   * @return The start.
   */
  long getStart();

  /**
   * <code>uint64 end = 3;</code>
   * @return The end.
   */
  long getEnd();
}
