// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/rpc/rpc.proto
// Protobuf Java Version: 4.29.1

package com.github.iotexproject.grpc.rpc;

/**
 * Protobuf enum {@code iotexrpc.MessageType}
 */
public enum MessageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN = 0;</code>
   */
  UNKNOWN(0),
  /**
   * <code>ACTION = 1;</code>
   */
  ACTION(1),
  /**
   * <code>BLOCK = 2;</code>
   */
  BLOCK(2),
  /**
   * <code>CONSENSUS = 3;</code>
   */
  CONSENSUS(3),
  /**
   * <code>BLOCK_REQUEST = 4;</code>
   */
  BLOCK_REQUEST(4),
  /**
   * <code>NODE_INFO_REQUEST = 5;</code>
   */
  NODE_INFO_REQUEST(5),
  /**
   * <code>NODE_INFO = 6;</code>
   */
  NODE_INFO(6),
  /**
   * <code>ACTIONS = 7;</code>
   */
  ACTIONS(7),
  /**
   * <code>ACTION_HASH = 8;</code>
   */
  ACTION_HASH(8),
  /**
   * <code>ACTION_REQUEST = 9;</code>
   */
  ACTION_REQUEST(9),
  /**
   * <code>TEST = 10001;</code>
   */
  TEST(10001),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      MessageType.class.getName());
  }
  /**
   * <code>UNKNOWN = 0;</code>
   */
  public static final int UNKNOWN_VALUE = 0;
  /**
   * <code>ACTION = 1;</code>
   */
  public static final int ACTION_VALUE = 1;
  /**
   * <code>BLOCK = 2;</code>
   */
  public static final int BLOCK_VALUE = 2;
  /**
   * <code>CONSENSUS = 3;</code>
   */
  public static final int CONSENSUS_VALUE = 3;
  /**
   * <code>BLOCK_REQUEST = 4;</code>
   */
  public static final int BLOCK_REQUEST_VALUE = 4;
  /**
   * <code>NODE_INFO_REQUEST = 5;</code>
   */
  public static final int NODE_INFO_REQUEST_VALUE = 5;
  /**
   * <code>NODE_INFO = 6;</code>
   */
  public static final int NODE_INFO_VALUE = 6;
  /**
   * <code>ACTIONS = 7;</code>
   */
  public static final int ACTIONS_VALUE = 7;
  /**
   * <code>ACTION_HASH = 8;</code>
   */
  public static final int ACTION_HASH_VALUE = 8;
  /**
   * <code>ACTION_REQUEST = 9;</code>
   */
  public static final int ACTION_REQUEST_VALUE = 9;
  /**
   * <code>TEST = 10001;</code>
   */
  public static final int TEST_VALUE = 10001;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MessageType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MessageType forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN;
      case 1: return ACTION;
      case 2: return BLOCK;
      case 3: return CONSENSUS;
      case 4: return BLOCK_REQUEST;
      case 5: return NODE_INFO_REQUEST;
      case 6: return NODE_INFO;
      case 7: return ACTIONS;
      case 8: return ACTION_HASH;
      case 9: return ACTION_REQUEST;
      case 10001: return TEST;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MessageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
          public MessageType findValueByNumber(int number) {
            return MessageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.github.iotexproject.grpc.rpc.Rpc.getDescriptor().getEnumTypes().get(0);
  }

  private static final MessageType[] VALUES = values();

  public static MessageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MessageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:iotexrpc.MessageType)
}

