// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/types/blockchain.proto
// Protobuf Java Version: 4.29.1

package com.github.iotexproject.grpc.types;

/**
 * <pre>
 * Block Metadata
 * </pre>
 *
 * Protobuf type {@code iotextypes.BlockMeta}
 */
public final class BlockMeta extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:iotextypes.BlockMeta)
    BlockMetaOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      BlockMeta.class.getName());
  }
  // Use BlockMeta.newBuilder() to construct.
  private BlockMeta(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BlockMeta() {
    hash_ = "";
    producerAddress_ = "";
    transferAmount_ = "";
    txRoot_ = "";
    receiptRoot_ = "";
    deltaStateDigest_ = "";
    logsBloom_ = "";
    previousBlockHash_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.iotexproject.grpc.types.Blockchain.internal_static_iotextypes_BlockMeta_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.iotexproject.grpc.types.Blockchain.internal_static_iotextypes_BlockMeta_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.iotexproject.grpc.types.BlockMeta.class, com.github.iotexproject.grpc.types.BlockMeta.Builder.class);
  }

  private int bitField0_;
  public static final int HASH_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object hash_ = "";
  /**
   * <code>string hash = 1;</code>
   * @return The hash.
   */
  @java.lang.Override
  public java.lang.String getHash() {
    java.lang.Object ref = hash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hash_ = s;
      return s;
    }
  }
  /**
   * <code>string hash = 1;</code>
   * @return The bytes for hash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHashBytes() {
    java.lang.Object ref = hash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HEIGHT_FIELD_NUMBER = 2;
  private long height_ = 0L;
  /**
   * <code>uint64 height = 2;</code>
   * @return The height.
   */
  @java.lang.Override
  public long getHeight() {
    return height_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 3;
  private com.google.protobuf.Timestamp timestamp_;
  /**
   * <code>.google.protobuf.Timestamp timestamp = 3;</code>
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 3;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }

  public static final int NUMACTIONS_FIELD_NUMBER = 4;
  private long numActions_ = 0L;
  /**
   * <code>int64 numActions = 4;</code>
   * @return The numActions.
   */
  @java.lang.Override
  public long getNumActions() {
    return numActions_;
  }

  public static final int PRODUCERADDRESS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object producerAddress_ = "";
  /**
   * <code>string producerAddress = 5;</code>
   * @return The producerAddress.
   */
  @java.lang.Override
  public java.lang.String getProducerAddress() {
    java.lang.Object ref = producerAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      producerAddress_ = s;
      return s;
    }
  }
  /**
   * <code>string producerAddress = 5;</code>
   * @return The bytes for producerAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProducerAddressBytes() {
    java.lang.Object ref = producerAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      producerAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSFERAMOUNT_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object transferAmount_ = "";
  /**
   * <code>string transferAmount = 6;</code>
   * @return The transferAmount.
   */
  @java.lang.Override
  public java.lang.String getTransferAmount() {
    java.lang.Object ref = transferAmount_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transferAmount_ = s;
      return s;
    }
  }
  /**
   * <code>string transferAmount = 6;</code>
   * @return The bytes for transferAmount.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTransferAmountBytes() {
    java.lang.Object ref = transferAmount_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transferAmount_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TXROOT_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object txRoot_ = "";
  /**
   * <code>string txRoot = 7;</code>
   * @return The txRoot.
   */
  @java.lang.Override
  public java.lang.String getTxRoot() {
    java.lang.Object ref = txRoot_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      txRoot_ = s;
      return s;
    }
  }
  /**
   * <code>string txRoot = 7;</code>
   * @return The bytes for txRoot.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTxRootBytes() {
    java.lang.Object ref = txRoot_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      txRoot_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECEIPTROOT_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object receiptRoot_ = "";
  /**
   * <code>string receiptRoot = 8;</code>
   * @return The receiptRoot.
   */
  @java.lang.Override
  public java.lang.String getReceiptRoot() {
    java.lang.Object ref = receiptRoot_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      receiptRoot_ = s;
      return s;
    }
  }
  /**
   * <code>string receiptRoot = 8;</code>
   * @return The bytes for receiptRoot.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReceiptRootBytes() {
    java.lang.Object ref = receiptRoot_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      receiptRoot_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DELTASTATEDIGEST_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object deltaStateDigest_ = "";
  /**
   * <code>string deltaStateDigest = 9;</code>
   * @return The deltaStateDigest.
   */
  @java.lang.Override
  public java.lang.String getDeltaStateDigest() {
    java.lang.Object ref = deltaStateDigest_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deltaStateDigest_ = s;
      return s;
    }
  }
  /**
   * <code>string deltaStateDigest = 9;</code>
   * @return The bytes for deltaStateDigest.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeltaStateDigestBytes() {
    java.lang.Object ref = deltaStateDigest_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deltaStateDigest_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOGSBLOOM_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object logsBloom_ = "";
  /**
   * <code>string logsBloom = 10;</code>
   * @return The logsBloom.
   */
  @java.lang.Override
  public java.lang.String getLogsBloom() {
    java.lang.Object ref = logsBloom_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      logsBloom_ = s;
      return s;
    }
  }
  /**
   * <code>string logsBloom = 10;</code>
   * @return The bytes for logsBloom.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLogsBloomBytes() {
    java.lang.Object ref = logsBloom_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      logsBloom_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PREVIOUSBLOCKHASH_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object previousBlockHash_ = "";
  /**
   * <code>string previousBlockHash = 11;</code>
   * @return The previousBlockHash.
   */
  @java.lang.Override
  public java.lang.String getPreviousBlockHash() {
    java.lang.Object ref = previousBlockHash_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      previousBlockHash_ = s;
      return s;
    }
  }
  /**
   * <code>string previousBlockHash = 11;</code>
   * @return The bytes for previousBlockHash.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPreviousBlockHashBytes() {
    java.lang.Object ref = previousBlockHash_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      previousBlockHash_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GASLIMIT_FIELD_NUMBER = 12;
  private long gasLimit_ = 0L;
  /**
   * <code>uint64 gasLimit = 12;</code>
   * @return The gasLimit.
   */
  @java.lang.Override
  public long getGasLimit() {
    return gasLimit_;
  }

  public static final int GASUSED_FIELD_NUMBER = 13;
  private long gasUsed_ = 0L;
  /**
   * <code>uint64 gasUsed = 13;</code>
   * @return The gasUsed.
   */
  @java.lang.Override
  public long getGasUsed() {
    return gasUsed_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(hash_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, hash_);
    }
    if (height_ != 0L) {
      output.writeUInt64(2, height_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getTimestamp());
    }
    if (numActions_ != 0L) {
      output.writeInt64(4, numActions_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(producerAddress_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, producerAddress_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(transferAmount_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, transferAmount_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(txRoot_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, txRoot_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(receiptRoot_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 8, receiptRoot_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deltaStateDigest_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, deltaStateDigest_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(logsBloom_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 10, logsBloom_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(previousBlockHash_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 11, previousBlockHash_);
    }
    if (gasLimit_ != 0L) {
      output.writeUInt64(12, gasLimit_);
    }
    if (gasUsed_ != 0L) {
      output.writeUInt64(13, gasUsed_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(hash_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, hash_);
    }
    if (height_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, height_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTimestamp());
    }
    if (numActions_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, numActions_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(producerAddress_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, producerAddress_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(transferAmount_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, transferAmount_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(txRoot_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(7, txRoot_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(receiptRoot_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(8, receiptRoot_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deltaStateDigest_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(9, deltaStateDigest_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(logsBloom_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(10, logsBloom_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(previousBlockHash_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(11, previousBlockHash_);
    }
    if (gasLimit_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(12, gasLimit_);
    }
    if (gasUsed_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(13, gasUsed_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.iotexproject.grpc.types.BlockMeta)) {
      return super.equals(obj);
    }
    com.github.iotexproject.grpc.types.BlockMeta other = (com.github.iotexproject.grpc.types.BlockMeta) obj;

    if (!getHash()
        .equals(other.getHash())) return false;
    if (getHeight()
        != other.getHeight()) return false;
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
    }
    if (getNumActions()
        != other.getNumActions()) return false;
    if (!getProducerAddress()
        .equals(other.getProducerAddress())) return false;
    if (!getTransferAmount()
        .equals(other.getTransferAmount())) return false;
    if (!getTxRoot()
        .equals(other.getTxRoot())) return false;
    if (!getReceiptRoot()
        .equals(other.getReceiptRoot())) return false;
    if (!getDeltaStateDigest()
        .equals(other.getDeltaStateDigest())) return false;
    if (!getLogsBloom()
        .equals(other.getLogsBloom())) return false;
    if (!getPreviousBlockHash()
        .equals(other.getPreviousBlockHash())) return false;
    if (getGasLimit()
        != other.getGasLimit()) return false;
    if (getGasUsed()
        != other.getGasUsed()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HASH_FIELD_NUMBER;
    hash = (53 * hash) + getHash().hashCode();
    hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getHeight());
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    hash = (37 * hash) + NUMACTIONS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNumActions());
    hash = (37 * hash) + PRODUCERADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getProducerAddress().hashCode();
    hash = (37 * hash) + TRANSFERAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getTransferAmount().hashCode();
    hash = (37 * hash) + TXROOT_FIELD_NUMBER;
    hash = (53 * hash) + getTxRoot().hashCode();
    hash = (37 * hash) + RECEIPTROOT_FIELD_NUMBER;
    hash = (53 * hash) + getReceiptRoot().hashCode();
    hash = (37 * hash) + DELTASTATEDIGEST_FIELD_NUMBER;
    hash = (53 * hash) + getDeltaStateDigest().hashCode();
    hash = (37 * hash) + LOGSBLOOM_FIELD_NUMBER;
    hash = (53 * hash) + getLogsBloom().hashCode();
    hash = (37 * hash) + PREVIOUSBLOCKHASH_FIELD_NUMBER;
    hash = (53 * hash) + getPreviousBlockHash().hashCode();
    hash = (37 * hash) + GASLIMIT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGasLimit());
    hash = (37 * hash) + GASUSED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getGasUsed());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.iotexproject.grpc.types.BlockMeta parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.types.BlockMeta parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.BlockMeta parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.types.BlockMeta parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.BlockMeta parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.types.BlockMeta parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.BlockMeta parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.types.BlockMeta parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.iotexproject.grpc.types.BlockMeta parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.iotexproject.grpc.types.BlockMeta parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.BlockMeta parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.types.BlockMeta parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.iotexproject.grpc.types.BlockMeta prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Block Metadata
   * </pre>
   *
   * Protobuf type {@code iotextypes.BlockMeta}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:iotextypes.BlockMeta)
      com.github.iotexproject.grpc.types.BlockMetaOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.iotexproject.grpc.types.Blockchain.internal_static_iotextypes_BlockMeta_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.iotexproject.grpc.types.Blockchain.internal_static_iotextypes_BlockMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.iotexproject.grpc.types.BlockMeta.class, com.github.iotexproject.grpc.types.BlockMeta.Builder.class);
    }

    // Construct using com.github.iotexproject.grpc.types.BlockMeta.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getTimestampFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      hash_ = "";
      height_ = 0L;
      timestamp_ = null;
      if (timestampBuilder_ != null) {
        timestampBuilder_.dispose();
        timestampBuilder_ = null;
      }
      numActions_ = 0L;
      producerAddress_ = "";
      transferAmount_ = "";
      txRoot_ = "";
      receiptRoot_ = "";
      deltaStateDigest_ = "";
      logsBloom_ = "";
      previousBlockHash_ = "";
      gasLimit_ = 0L;
      gasUsed_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.iotexproject.grpc.types.Blockchain.internal_static_iotextypes_BlockMeta_descriptor;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.types.BlockMeta getDefaultInstanceForType() {
      return com.github.iotexproject.grpc.types.BlockMeta.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.types.BlockMeta build() {
      com.github.iotexproject.grpc.types.BlockMeta result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.types.BlockMeta buildPartial() {
      com.github.iotexproject.grpc.types.BlockMeta result = new com.github.iotexproject.grpc.types.BlockMeta(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.github.iotexproject.grpc.types.BlockMeta result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.hash_ = hash_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.height_ = height_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.timestamp_ = timestampBuilder_ == null
            ? timestamp_
            : timestampBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.numActions_ = numActions_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.producerAddress_ = producerAddress_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.transferAmount_ = transferAmount_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.txRoot_ = txRoot_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.receiptRoot_ = receiptRoot_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.deltaStateDigest_ = deltaStateDigest_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.logsBloom_ = logsBloom_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.previousBlockHash_ = previousBlockHash_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.gasLimit_ = gasLimit_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.gasUsed_ = gasUsed_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.iotexproject.grpc.types.BlockMeta) {
        return mergeFrom((com.github.iotexproject.grpc.types.BlockMeta)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.iotexproject.grpc.types.BlockMeta other) {
      if (other == com.github.iotexproject.grpc.types.BlockMeta.getDefaultInstance()) return this;
      if (!other.getHash().isEmpty()) {
        hash_ = other.hash_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getHeight() != 0L) {
        setHeight(other.getHeight());
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      if (other.getNumActions() != 0L) {
        setNumActions(other.getNumActions());
      }
      if (!other.getProducerAddress().isEmpty()) {
        producerAddress_ = other.producerAddress_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getTransferAmount().isEmpty()) {
        transferAmount_ = other.transferAmount_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getTxRoot().isEmpty()) {
        txRoot_ = other.txRoot_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getReceiptRoot().isEmpty()) {
        receiptRoot_ = other.receiptRoot_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getDeltaStateDigest().isEmpty()) {
        deltaStateDigest_ = other.deltaStateDigest_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getLogsBloom().isEmpty()) {
        logsBloom_ = other.logsBloom_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (!other.getPreviousBlockHash().isEmpty()) {
        previousBlockHash_ = other.previousBlockHash_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (other.getGasLimit() != 0L) {
        setGasLimit(other.getGasLimit());
      }
      if (other.getGasUsed() != 0L) {
        setGasUsed(other.getGasUsed());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              hash_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              height_ = input.readUInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getTimestampFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              numActions_ = input.readInt64();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              producerAddress_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              transferAmount_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              txRoot_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              receiptRoot_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              deltaStateDigest_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              logsBloom_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              previousBlockHash_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 96: {
              gasLimit_ = input.readUInt64();
              bitField0_ |= 0x00000800;
              break;
            } // case 96
            case 104: {
              gasUsed_ = input.readUInt64();
              bitField0_ |= 0x00001000;
              break;
            } // case 104
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object hash_ = "";
    /**
     * <code>string hash = 1;</code>
     * @return The hash.
     */
    public java.lang.String getHash() {
      java.lang.Object ref = hash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hash = 1;</code>
     * @return The bytes for hash.
     */
    public com.google.protobuf.ByteString
        getHashBytes() {
      java.lang.Object ref = hash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hash = 1;</code>
     * @param value The hash to set.
     * @return This builder for chaining.
     */
    public Builder setHash(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      hash_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string hash = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHash() {
      hash_ = getDefaultInstance().getHash();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string hash = 1;</code>
     * @param value The bytes for hash to set.
     * @return This builder for chaining.
     */
    public Builder setHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      hash_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private long height_ ;
    /**
     * <code>uint64 height = 2;</code>
     * @return The height.
     */
    @java.lang.Override
    public long getHeight() {
      return height_;
    }
    /**
     * <code>uint64 height = 2;</code>
     * @param value The height to set.
     * @return This builder for chaining.
     */
    public Builder setHeight(long value) {

      height_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 height = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeight() {
      bitField0_ = (bitField0_ & ~0x00000002);
      height_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp timestamp_;
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     * @return The timestamp.
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
      } else {
        timestampBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public Builder setTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          timestamp_ != null &&
          timestamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getTimestampBuilder().mergeFrom(value);
        } else {
          timestamp_ = value;
        }
      } else {
        timestampBuilder_.mergeFrom(value);
      }
      if (timestamp_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000004);
      timestamp_ = null;
      if (timestampBuilder_ != null) {
        timestampBuilder_.dispose();
        timestampBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    private long numActions_ ;
    /**
     * <code>int64 numActions = 4;</code>
     * @return The numActions.
     */
    @java.lang.Override
    public long getNumActions() {
      return numActions_;
    }
    /**
     * <code>int64 numActions = 4;</code>
     * @param value The numActions to set.
     * @return This builder for chaining.
     */
    public Builder setNumActions(long value) {

      numActions_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int64 numActions = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumActions() {
      bitField0_ = (bitField0_ & ~0x00000008);
      numActions_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object producerAddress_ = "";
    /**
     * <code>string producerAddress = 5;</code>
     * @return The producerAddress.
     */
    public java.lang.String getProducerAddress() {
      java.lang.Object ref = producerAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        producerAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string producerAddress = 5;</code>
     * @return The bytes for producerAddress.
     */
    public com.google.protobuf.ByteString
        getProducerAddressBytes() {
      java.lang.Object ref = producerAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        producerAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string producerAddress = 5;</code>
     * @param value The producerAddress to set.
     * @return This builder for chaining.
     */
    public Builder setProducerAddress(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      producerAddress_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string producerAddress = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearProducerAddress() {
      producerAddress_ = getDefaultInstance().getProducerAddress();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string producerAddress = 5;</code>
     * @param value The bytes for producerAddress to set.
     * @return This builder for chaining.
     */
    public Builder setProducerAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      producerAddress_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object transferAmount_ = "";
    /**
     * <code>string transferAmount = 6;</code>
     * @return The transferAmount.
     */
    public java.lang.String getTransferAmount() {
      java.lang.Object ref = transferAmount_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transferAmount_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string transferAmount = 6;</code>
     * @return The bytes for transferAmount.
     */
    public com.google.protobuf.ByteString
        getTransferAmountBytes() {
      java.lang.Object ref = transferAmount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transferAmount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transferAmount = 6;</code>
     * @param value The transferAmount to set.
     * @return This builder for chaining.
     */
    public Builder setTransferAmount(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      transferAmount_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string transferAmount = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransferAmount() {
      transferAmount_ = getDefaultInstance().getTransferAmount();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string transferAmount = 6;</code>
     * @param value The bytes for transferAmount to set.
     * @return This builder for chaining.
     */
    public Builder setTransferAmountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      transferAmount_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object txRoot_ = "";
    /**
     * <code>string txRoot = 7;</code>
     * @return The txRoot.
     */
    public java.lang.String getTxRoot() {
      java.lang.Object ref = txRoot_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txRoot_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string txRoot = 7;</code>
     * @return The bytes for txRoot.
     */
    public com.google.protobuf.ByteString
        getTxRootBytes() {
      java.lang.Object ref = txRoot_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txRoot_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string txRoot = 7;</code>
     * @param value The txRoot to set.
     * @return This builder for chaining.
     */
    public Builder setTxRoot(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      txRoot_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string txRoot = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTxRoot() {
      txRoot_ = getDefaultInstance().getTxRoot();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string txRoot = 7;</code>
     * @param value The bytes for txRoot to set.
     * @return This builder for chaining.
     */
    public Builder setTxRootBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      txRoot_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object receiptRoot_ = "";
    /**
     * <code>string receiptRoot = 8;</code>
     * @return The receiptRoot.
     */
    public java.lang.String getReceiptRoot() {
      java.lang.Object ref = receiptRoot_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiptRoot_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string receiptRoot = 8;</code>
     * @return The bytes for receiptRoot.
     */
    public com.google.protobuf.ByteString
        getReceiptRootBytes() {
      java.lang.Object ref = receiptRoot_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiptRoot_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string receiptRoot = 8;</code>
     * @param value The receiptRoot to set.
     * @return This builder for chaining.
     */
    public Builder setReceiptRoot(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      receiptRoot_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string receiptRoot = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiptRoot() {
      receiptRoot_ = getDefaultInstance().getReceiptRoot();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string receiptRoot = 8;</code>
     * @param value The bytes for receiptRoot to set.
     * @return This builder for chaining.
     */
    public Builder setReceiptRootBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      receiptRoot_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object deltaStateDigest_ = "";
    /**
     * <code>string deltaStateDigest = 9;</code>
     * @return The deltaStateDigest.
     */
    public java.lang.String getDeltaStateDigest() {
      java.lang.Object ref = deltaStateDigest_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deltaStateDigest_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string deltaStateDigest = 9;</code>
     * @return The bytes for deltaStateDigest.
     */
    public com.google.protobuf.ByteString
        getDeltaStateDigestBytes() {
      java.lang.Object ref = deltaStateDigest_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deltaStateDigest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string deltaStateDigest = 9;</code>
     * @param value The deltaStateDigest to set.
     * @return This builder for chaining.
     */
    public Builder setDeltaStateDigest(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      deltaStateDigest_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string deltaStateDigest = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeltaStateDigest() {
      deltaStateDigest_ = getDefaultInstance().getDeltaStateDigest();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string deltaStateDigest = 9;</code>
     * @param value The bytes for deltaStateDigest to set.
     * @return This builder for chaining.
     */
    public Builder setDeltaStateDigestBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      deltaStateDigest_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object logsBloom_ = "";
    /**
     * <code>string logsBloom = 10;</code>
     * @return The logsBloom.
     */
    public java.lang.String getLogsBloom() {
      java.lang.Object ref = logsBloom_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logsBloom_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string logsBloom = 10;</code>
     * @return The bytes for logsBloom.
     */
    public com.google.protobuf.ByteString
        getLogsBloomBytes() {
      java.lang.Object ref = logsBloom_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logsBloom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string logsBloom = 10;</code>
     * @param value The logsBloom to set.
     * @return This builder for chaining.
     */
    public Builder setLogsBloom(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      logsBloom_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>string logsBloom = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearLogsBloom() {
      logsBloom_ = getDefaultInstance().getLogsBloom();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }
    /**
     * <code>string logsBloom = 10;</code>
     * @param value The bytes for logsBloom to set.
     * @return This builder for chaining.
     */
    public Builder setLogsBloomBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      logsBloom_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private java.lang.Object previousBlockHash_ = "";
    /**
     * <code>string previousBlockHash = 11;</code>
     * @return The previousBlockHash.
     */
    public java.lang.String getPreviousBlockHash() {
      java.lang.Object ref = previousBlockHash_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        previousBlockHash_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string previousBlockHash = 11;</code>
     * @return The bytes for previousBlockHash.
     */
    public com.google.protobuf.ByteString
        getPreviousBlockHashBytes() {
      java.lang.Object ref = previousBlockHash_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        previousBlockHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string previousBlockHash = 11;</code>
     * @param value The previousBlockHash to set.
     * @return This builder for chaining.
     */
    public Builder setPreviousBlockHash(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      previousBlockHash_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>string previousBlockHash = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearPreviousBlockHash() {
      previousBlockHash_ = getDefaultInstance().getPreviousBlockHash();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>string previousBlockHash = 11;</code>
     * @param value The bytes for previousBlockHash to set.
     * @return This builder for chaining.
     */
    public Builder setPreviousBlockHashBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      previousBlockHash_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private long gasLimit_ ;
    /**
     * <code>uint64 gasLimit = 12;</code>
     * @return The gasLimit.
     */
    @java.lang.Override
    public long getGasLimit() {
      return gasLimit_;
    }
    /**
     * <code>uint64 gasLimit = 12;</code>
     * @param value The gasLimit to set.
     * @return This builder for chaining.
     */
    public Builder setGasLimit(long value) {

      gasLimit_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 gasLimit = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearGasLimit() {
      bitField0_ = (bitField0_ & ~0x00000800);
      gasLimit_ = 0L;
      onChanged();
      return this;
    }

    private long gasUsed_ ;
    /**
     * <code>uint64 gasUsed = 13;</code>
     * @return The gasUsed.
     */
    @java.lang.Override
    public long getGasUsed() {
      return gasUsed_;
    }
    /**
     * <code>uint64 gasUsed = 13;</code>
     * @param value The gasUsed to set.
     * @return This builder for chaining.
     */
    public Builder setGasUsed(long value) {

      gasUsed_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 gasUsed = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearGasUsed() {
      bitField0_ = (bitField0_ & ~0x00001000);
      gasUsed_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:iotextypes.BlockMeta)
  }

  // @@protoc_insertion_point(class_scope:iotextypes.BlockMeta)
  private static final com.github.iotexproject.grpc.types.BlockMeta DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.iotexproject.grpc.types.BlockMeta();
  }

  public static com.github.iotexproject.grpc.types.BlockMeta getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BlockMeta>
      PARSER = new com.google.protobuf.AbstractParser<BlockMeta>() {
    @java.lang.Override
    public BlockMeta parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BlockMeta> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BlockMeta> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.iotexproject.grpc.types.BlockMeta getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

