// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/types/action.proto
// Protobuf Java Version: 4.29.1

package com.github.iotexproject.grpc.types;

/**
 * Protobuf type {@code iotextypes.CandidateRegister}
 */
public final class CandidateRegister extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:iotextypes.CandidateRegister)
    CandidateRegisterOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      CandidateRegister.class.getName());
  }
  // Use CandidateRegister.newBuilder() to construct.
  private CandidateRegister(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CandidateRegister() {
    stakedAmount_ = "";
    ownerAddress_ = "";
    payload_ = com.google.protobuf.ByteString.EMPTY;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.iotexproject.grpc.types.ActionOuterClass.internal_static_iotextypes_CandidateRegister_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.iotexproject.grpc.types.ActionOuterClass.internal_static_iotextypes_CandidateRegister_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.iotexproject.grpc.types.CandidateRegister.class, com.github.iotexproject.grpc.types.CandidateRegister.Builder.class);
  }

  private int bitField0_;
  public static final int CANDIDATE_FIELD_NUMBER = 1;
  private com.github.iotexproject.grpc.types.CandidateBasicInfo candidate_;
  /**
   * <code>.iotextypes.CandidateBasicInfo candidate = 1;</code>
   * @return Whether the candidate field is set.
   */
  @java.lang.Override
  public boolean hasCandidate() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.iotextypes.CandidateBasicInfo candidate = 1;</code>
   * @return The candidate.
   */
  @java.lang.Override
  public com.github.iotexproject.grpc.types.CandidateBasicInfo getCandidate() {
    return candidate_ == null ? com.github.iotexproject.grpc.types.CandidateBasicInfo.getDefaultInstance() : candidate_;
  }
  /**
   * <code>.iotextypes.CandidateBasicInfo candidate = 1;</code>
   */
  @java.lang.Override
  public com.github.iotexproject.grpc.types.CandidateBasicInfoOrBuilder getCandidateOrBuilder() {
    return candidate_ == null ? com.github.iotexproject.grpc.types.CandidateBasicInfo.getDefaultInstance() : candidate_;
  }

  public static final int STAKEDAMOUNT_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object stakedAmount_ = "";
  /**
   * <code>string stakedAmount = 2;</code>
   * @return The stakedAmount.
   */
  @java.lang.Override
  public java.lang.String getStakedAmount() {
    java.lang.Object ref = stakedAmount_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      stakedAmount_ = s;
      return s;
    }
  }
  /**
   * <code>string stakedAmount = 2;</code>
   * @return The bytes for stakedAmount.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStakedAmountBytes() {
    java.lang.Object ref = stakedAmount_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stakedAmount_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STAKEDDURATION_FIELD_NUMBER = 3;
  private int stakedDuration_ = 0;
  /**
   * <code>uint32 stakedDuration = 3;</code>
   * @return The stakedDuration.
   */
  @java.lang.Override
  public int getStakedDuration() {
    return stakedDuration_;
  }

  public static final int AUTOSTAKE_FIELD_NUMBER = 4;
  private boolean autoStake_ = false;
  /**
   * <code>bool autoStake = 4;</code>
   * @return The autoStake.
   */
  @java.lang.Override
  public boolean getAutoStake() {
    return autoStake_;
  }

  public static final int OWNERADDRESS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ownerAddress_ = "";
  /**
   * <pre>
   * if ownerAddress is absent, owner of candidate is the sender
   * </pre>
   *
   * <code>string ownerAddress = 5;</code>
   * @return The ownerAddress.
   */
  @java.lang.Override
  public java.lang.String getOwnerAddress() {
    java.lang.Object ref = ownerAddress_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ownerAddress_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * if ownerAddress is absent, owner of candidate is the sender
   * </pre>
   *
   * <code>string ownerAddress = 5;</code>
   * @return The bytes for ownerAddress.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOwnerAddressBytes() {
    java.lang.Object ref = ownerAddress_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ownerAddress_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAYLOAD_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes payload = 6;</code>
   * @return The payload.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPayload() {
    return payload_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getCandidate());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(stakedAmount_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, stakedAmount_);
    }
    if (stakedDuration_ != 0) {
      output.writeUInt32(3, stakedDuration_);
    }
    if (autoStake_ != false) {
      output.writeBool(4, autoStake_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ownerAddress_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, ownerAddress_);
    }
    if (!payload_.isEmpty()) {
      output.writeBytes(6, payload_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCandidate());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(stakedAmount_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, stakedAmount_);
    }
    if (stakedDuration_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, stakedDuration_);
    }
    if (autoStake_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, autoStake_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ownerAddress_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, ownerAddress_);
    }
    if (!payload_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, payload_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.iotexproject.grpc.types.CandidateRegister)) {
      return super.equals(obj);
    }
    com.github.iotexproject.grpc.types.CandidateRegister other = (com.github.iotexproject.grpc.types.CandidateRegister) obj;

    if (hasCandidate() != other.hasCandidate()) return false;
    if (hasCandidate()) {
      if (!getCandidate()
          .equals(other.getCandidate())) return false;
    }
    if (!getStakedAmount()
        .equals(other.getStakedAmount())) return false;
    if (getStakedDuration()
        != other.getStakedDuration()) return false;
    if (getAutoStake()
        != other.getAutoStake()) return false;
    if (!getOwnerAddress()
        .equals(other.getOwnerAddress())) return false;
    if (!getPayload()
        .equals(other.getPayload())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCandidate()) {
      hash = (37 * hash) + CANDIDATE_FIELD_NUMBER;
      hash = (53 * hash) + getCandidate().hashCode();
    }
    hash = (37 * hash) + STAKEDAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getStakedAmount().hashCode();
    hash = (37 * hash) + STAKEDDURATION_FIELD_NUMBER;
    hash = (53 * hash) + getStakedDuration();
    hash = (37 * hash) + AUTOSTAKE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAutoStake());
    hash = (37 * hash) + OWNERADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + getOwnerAddress().hashCode();
    hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getPayload().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.iotexproject.grpc.types.CandidateRegister parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.types.CandidateRegister parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.CandidateRegister parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.types.CandidateRegister parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.CandidateRegister parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.types.CandidateRegister parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.CandidateRegister parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.types.CandidateRegister parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.iotexproject.grpc.types.CandidateRegister parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.iotexproject.grpc.types.CandidateRegister parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.CandidateRegister parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.types.CandidateRegister parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.iotexproject.grpc.types.CandidateRegister prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code iotextypes.CandidateRegister}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:iotextypes.CandidateRegister)
      com.github.iotexproject.grpc.types.CandidateRegisterOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.iotexproject.grpc.types.ActionOuterClass.internal_static_iotextypes_CandidateRegister_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.iotexproject.grpc.types.ActionOuterClass.internal_static_iotextypes_CandidateRegister_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.iotexproject.grpc.types.CandidateRegister.class, com.github.iotexproject.grpc.types.CandidateRegister.Builder.class);
    }

    // Construct using com.github.iotexproject.grpc.types.CandidateRegister.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getCandidateFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      candidate_ = null;
      if (candidateBuilder_ != null) {
        candidateBuilder_.dispose();
        candidateBuilder_ = null;
      }
      stakedAmount_ = "";
      stakedDuration_ = 0;
      autoStake_ = false;
      ownerAddress_ = "";
      payload_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.iotexproject.grpc.types.ActionOuterClass.internal_static_iotextypes_CandidateRegister_descriptor;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.types.CandidateRegister getDefaultInstanceForType() {
      return com.github.iotexproject.grpc.types.CandidateRegister.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.types.CandidateRegister build() {
      com.github.iotexproject.grpc.types.CandidateRegister result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.types.CandidateRegister buildPartial() {
      com.github.iotexproject.grpc.types.CandidateRegister result = new com.github.iotexproject.grpc.types.CandidateRegister(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.github.iotexproject.grpc.types.CandidateRegister result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.candidate_ = candidateBuilder_ == null
            ? candidate_
            : candidateBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.stakedAmount_ = stakedAmount_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.stakedDuration_ = stakedDuration_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.autoStake_ = autoStake_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.ownerAddress_ = ownerAddress_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.payload_ = payload_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.iotexproject.grpc.types.CandidateRegister) {
        return mergeFrom((com.github.iotexproject.grpc.types.CandidateRegister)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.iotexproject.grpc.types.CandidateRegister other) {
      if (other == com.github.iotexproject.grpc.types.CandidateRegister.getDefaultInstance()) return this;
      if (other.hasCandidate()) {
        mergeCandidate(other.getCandidate());
      }
      if (!other.getStakedAmount().isEmpty()) {
        stakedAmount_ = other.stakedAmount_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getStakedDuration() != 0) {
        setStakedDuration(other.getStakedDuration());
      }
      if (other.getAutoStake() != false) {
        setAutoStake(other.getAutoStake());
      }
      if (!other.getOwnerAddress().isEmpty()) {
        ownerAddress_ = other.ownerAddress_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
        setPayload(other.getPayload());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getCandidateFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              stakedAmount_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              stakedDuration_ = input.readUInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              autoStake_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              ownerAddress_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              payload_ = input.readBytes();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.github.iotexproject.grpc.types.CandidateBasicInfo candidate_;
    private com.google.protobuf.SingleFieldBuilder<
        com.github.iotexproject.grpc.types.CandidateBasicInfo, com.github.iotexproject.grpc.types.CandidateBasicInfo.Builder, com.github.iotexproject.grpc.types.CandidateBasicInfoOrBuilder> candidateBuilder_;
    /**
     * <code>.iotextypes.CandidateBasicInfo candidate = 1;</code>
     * @return Whether the candidate field is set.
     */
    public boolean hasCandidate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.iotextypes.CandidateBasicInfo candidate = 1;</code>
     * @return The candidate.
     */
    public com.github.iotexproject.grpc.types.CandidateBasicInfo getCandidate() {
      if (candidateBuilder_ == null) {
        return candidate_ == null ? com.github.iotexproject.grpc.types.CandidateBasicInfo.getDefaultInstance() : candidate_;
      } else {
        return candidateBuilder_.getMessage();
      }
    }
    /**
     * <code>.iotextypes.CandidateBasicInfo candidate = 1;</code>
     */
    public Builder setCandidate(com.github.iotexproject.grpc.types.CandidateBasicInfo value) {
      if (candidateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        candidate_ = value;
      } else {
        candidateBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.iotextypes.CandidateBasicInfo candidate = 1;</code>
     */
    public Builder setCandidate(
        com.github.iotexproject.grpc.types.CandidateBasicInfo.Builder builderForValue) {
      if (candidateBuilder_ == null) {
        candidate_ = builderForValue.build();
      } else {
        candidateBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.iotextypes.CandidateBasicInfo candidate = 1;</code>
     */
    public Builder mergeCandidate(com.github.iotexproject.grpc.types.CandidateBasicInfo value) {
      if (candidateBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          candidate_ != null &&
          candidate_ != com.github.iotexproject.grpc.types.CandidateBasicInfo.getDefaultInstance()) {
          getCandidateBuilder().mergeFrom(value);
        } else {
          candidate_ = value;
        }
      } else {
        candidateBuilder_.mergeFrom(value);
      }
      if (candidate_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.iotextypes.CandidateBasicInfo candidate = 1;</code>
     */
    public Builder clearCandidate() {
      bitField0_ = (bitField0_ & ~0x00000001);
      candidate_ = null;
      if (candidateBuilder_ != null) {
        candidateBuilder_.dispose();
        candidateBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.iotextypes.CandidateBasicInfo candidate = 1;</code>
     */
    public com.github.iotexproject.grpc.types.CandidateBasicInfo.Builder getCandidateBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getCandidateFieldBuilder().getBuilder();
    }
    /**
     * <code>.iotextypes.CandidateBasicInfo candidate = 1;</code>
     */
    public com.github.iotexproject.grpc.types.CandidateBasicInfoOrBuilder getCandidateOrBuilder() {
      if (candidateBuilder_ != null) {
        return candidateBuilder_.getMessageOrBuilder();
      } else {
        return candidate_ == null ?
            com.github.iotexproject.grpc.types.CandidateBasicInfo.getDefaultInstance() : candidate_;
      }
    }
    /**
     * <code>.iotextypes.CandidateBasicInfo candidate = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.github.iotexproject.grpc.types.CandidateBasicInfo, com.github.iotexproject.grpc.types.CandidateBasicInfo.Builder, com.github.iotexproject.grpc.types.CandidateBasicInfoOrBuilder> 
        getCandidateFieldBuilder() {
      if (candidateBuilder_ == null) {
        candidateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.github.iotexproject.grpc.types.CandidateBasicInfo, com.github.iotexproject.grpc.types.CandidateBasicInfo.Builder, com.github.iotexproject.grpc.types.CandidateBasicInfoOrBuilder>(
                getCandidate(),
                getParentForChildren(),
                isClean());
        candidate_ = null;
      }
      return candidateBuilder_;
    }

    private java.lang.Object stakedAmount_ = "";
    /**
     * <code>string stakedAmount = 2;</code>
     * @return The stakedAmount.
     */
    public java.lang.String getStakedAmount() {
      java.lang.Object ref = stakedAmount_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        stakedAmount_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string stakedAmount = 2;</code>
     * @return The bytes for stakedAmount.
     */
    public com.google.protobuf.ByteString
        getStakedAmountBytes() {
      java.lang.Object ref = stakedAmount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stakedAmount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string stakedAmount = 2;</code>
     * @param value The stakedAmount to set.
     * @return This builder for chaining.
     */
    public Builder setStakedAmount(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      stakedAmount_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string stakedAmount = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearStakedAmount() {
      stakedAmount_ = getDefaultInstance().getStakedAmount();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string stakedAmount = 2;</code>
     * @param value The bytes for stakedAmount to set.
     * @return This builder for chaining.
     */
    public Builder setStakedAmountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      stakedAmount_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int stakedDuration_ ;
    /**
     * <code>uint32 stakedDuration = 3;</code>
     * @return The stakedDuration.
     */
    @java.lang.Override
    public int getStakedDuration() {
      return stakedDuration_;
    }
    /**
     * <code>uint32 stakedDuration = 3;</code>
     * @param value The stakedDuration to set.
     * @return This builder for chaining.
     */
    public Builder setStakedDuration(int value) {

      stakedDuration_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 stakedDuration = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearStakedDuration() {
      bitField0_ = (bitField0_ & ~0x00000004);
      stakedDuration_ = 0;
      onChanged();
      return this;
    }

    private boolean autoStake_ ;
    /**
     * <code>bool autoStake = 4;</code>
     * @return The autoStake.
     */
    @java.lang.Override
    public boolean getAutoStake() {
      return autoStake_;
    }
    /**
     * <code>bool autoStake = 4;</code>
     * @param value The autoStake to set.
     * @return This builder for chaining.
     */
    public Builder setAutoStake(boolean value) {

      autoStake_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bool autoStake = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAutoStake() {
      bitField0_ = (bitField0_ & ~0x00000008);
      autoStake_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object ownerAddress_ = "";
    /**
     * <pre>
     * if ownerAddress is absent, owner of candidate is the sender
     * </pre>
     *
     * <code>string ownerAddress = 5;</code>
     * @return The ownerAddress.
     */
    public java.lang.String getOwnerAddress() {
      java.lang.Object ref = ownerAddress_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ownerAddress_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * if ownerAddress is absent, owner of candidate is the sender
     * </pre>
     *
     * <code>string ownerAddress = 5;</code>
     * @return The bytes for ownerAddress.
     */
    public com.google.protobuf.ByteString
        getOwnerAddressBytes() {
      java.lang.Object ref = ownerAddress_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ownerAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * if ownerAddress is absent, owner of candidate is the sender
     * </pre>
     *
     * <code>string ownerAddress = 5;</code>
     * @param value The ownerAddress to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerAddress(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ownerAddress_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * if ownerAddress is absent, owner of candidate is the sender
     * </pre>
     *
     * <code>string ownerAddress = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnerAddress() {
      ownerAddress_ = getDefaultInstance().getOwnerAddress();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * if ownerAddress is absent, owner of candidate is the sender
     * </pre>
     *
     * <code>string ownerAddress = 5;</code>
     * @param value The bytes for ownerAddress to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ownerAddress_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes payload = 6;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }
    /**
     * <code>bytes payload = 6;</code>
     * @param value The payload to set.
     * @return This builder for chaining.
     */
    public Builder setPayload(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      payload_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bytes payload = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayload() {
      bitField0_ = (bitField0_ & ~0x00000020);
      payload_ = getDefaultInstance().getPayload();
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:iotextypes.CandidateRegister)
  }

  // @@protoc_insertion_point(class_scope:iotextypes.CandidateRegister)
  private static final com.github.iotexproject.grpc.types.CandidateRegister DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.iotexproject.grpc.types.CandidateRegister();
  }

  public static com.github.iotexproject.grpc.types.CandidateRegister getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CandidateRegister>
      PARSER = new com.google.protobuf.AbstractParser<CandidateRegister>() {
    @java.lang.Override
    public CandidateRegister parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CandidateRegister> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CandidateRegister> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.iotexproject.grpc.types.CandidateRegister getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

