// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/types/blockchain.proto
// Protobuf Java Version: 4.29.1

package com.github.iotexproject.grpc.types;

public interface ChainMetaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:iotextypes.ChainMeta)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 height = 1;</code>
   * @return The height.
   */
  long getHeight();

  /**
   * <code>int64 numActions = 2;</code>
   * @return The numActions.
   */
  long getNumActions();

  /**
   * <code>int64 tps = 3;</code>
   * @return The tps.
   */
  long getTps();

  /**
   * <code>.iotextypes.EpochData epoch = 4;</code>
   * @return Whether the epoch field is set.
   */
  boolean hasEpoch();
  /**
   * <code>.iotextypes.EpochData epoch = 4;</code>
   * @return The epoch.
   */
  com.github.iotexproject.grpc.types.EpochData getEpoch();
  /**
   * <code>.iotextypes.EpochData epoch = 4;</code>
   */
  com.github.iotexproject.grpc.types.EpochDataOrBuilder getEpochOrBuilder();

  /**
   * <code>float tpsFloat = 5;</code>
   * @return The tpsFloat.
   */
  float getTpsFloat();

  /**
   * <code>uint32 chainID = 6;</code>
   * @return The chainID.
   */
  int getChainID();
}
