// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/types/genesis.proto
// Protobuf Java Version: 4.29.1

package com.github.iotexproject.grpc.types;

public final class GenesisOuterClass {
  private GenesisOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      GenesisOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iotextypes_Genesis_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_iotextypes_Genesis_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iotextypes_GenesisBlockchain_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_iotextypes_GenesisBlockchain_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iotextypes_GenesisAccount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_iotextypes_GenesisAccount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iotextypes_GenesisPoll_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_iotextypes_GenesisPoll_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iotextypes_GenesisDelegate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_iotextypes_GenesisDelegate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_iotextypes_GenesisRewarding_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_iotextypes_GenesisRewarding_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031proto/types/genesis.proto\022\niotextypes\"" +
      "\301\001\n\007Genesis\0221\n\nblockchain\030\001 \001(\0132\035.iotext" +
      "ypes.GenesisBlockchain\022+\n\007account\030\002 \001(\0132" +
      "\032.iotextypes.GenesisAccount\022%\n\004poll\030\003 \001(" +
      "\0132\027.iotextypes.GenesisPoll\022/\n\trewarding\030" +
      "\004 \001(\0132\034.iotextypes.GenesisRewarding\"\322\001\n\021" +
      "GenesisBlockchain\022\021\n\ttimestamp\030\001 \001(\003\022\025\n\r" +
      "blockGasLimit\030\002 \001(\004\022\026\n\016actionGasLimit\030\003 " +
      "\001(\004\022\025\n\rblockInterval\030\004 \001(\003\022\024\n\014numSubEpoc" +
      "hs\030\005 \001(\004\022\024\n\014numDelegates\030\006 \001(\004\022\035\n\025numCan" +
      "didateDelegates\030\007 \001(\004\022\031\n\021timeBasedRotati" +
      "on\030\010 \001(\010\"@\n\016GenesisAccount\022\030\n\020initBalanc" +
      "eAddrs\030\001 \003(\t\022\024\n\014initBalances\030\002 \003(\t\"\216\002\n\013G" +
      "enesisPoll\022 \n\030enableGravityChainVoting\030\001" +
      " \001(\010\022\037\n\027gravityChainStartHeight\030\002 \001(\004\022\037\n" +
      "\027registerContractAddress\030\003 \001(\t\022\036\n\026stakin" +
      "gContractAddress\030\004 \001(\t\022\025\n\rvoteThreshold\030" +
      "\005 \001(\t\022\026\n\016scoreThreshold\030\006 \001(\t\022\034\n\024selfSta" +
      "kingThreshold\030\007 \001(\t\022.\n\tdelegates\030\010 \003(\0132\033" +
      ".iotextypes.GenesisDelegate\"J\n\017GenesisDe" +
      "legate\022\024\n\014operatorAddr\030\001 \001(\t\022\022\n\nrewardAd" +
      "dr\030\002 \001(\t\022\r\n\005votes\030\003 \001(\t\"\216\002\n\020GenesisRewar" +
      "ding\022\025\n\rinitAdminAddr\030\001 \001(\t\022\023\n\013initBalan" +
      "ce\030\002 \001(\t\022\023\n\013blockReward\030\003 \001(\t\022\023\n\013epochRe" +
      "ward\030\004 \001(\t\022\"\n\032numDelegatesForEpochReward" +
      "\030\005 \001(\004\022\027\n\017foundationBonus\030\006 \001(\t\022&\n\036numDe" +
      "legatesForFoundationBonus\030\007 \001(\004\022 \n\030found" +
      "ationBonusLastEpoch\030\010 \001(\004\022\035\n\025productivit" +
      "yThreshold\030\t \001(\004B]\n\"com.github.iotexproj" +
      "ect.grpc.typesP\001Z5github.com/iotexprojec" +
      "t/iotex-proto/golang/iotextypesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_iotextypes_Genesis_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_iotextypes_Genesis_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_iotextypes_Genesis_descriptor,
        new java.lang.String[] { "Blockchain", "Account", "Poll", "Rewarding", });
    internal_static_iotextypes_GenesisBlockchain_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_iotextypes_GenesisBlockchain_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_iotextypes_GenesisBlockchain_descriptor,
        new java.lang.String[] { "Timestamp", "BlockGasLimit", "ActionGasLimit", "BlockInterval", "NumSubEpochs", "NumDelegates", "NumCandidateDelegates", "TimeBasedRotation", });
    internal_static_iotextypes_GenesisAccount_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_iotextypes_GenesisAccount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_iotextypes_GenesisAccount_descriptor,
        new java.lang.String[] { "InitBalanceAddrs", "InitBalances", });
    internal_static_iotextypes_GenesisPoll_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_iotextypes_GenesisPoll_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_iotextypes_GenesisPoll_descriptor,
        new java.lang.String[] { "EnableGravityChainVoting", "GravityChainStartHeight", "RegisterContractAddress", "StakingContractAddress", "VoteThreshold", "ScoreThreshold", "SelfStakingThreshold", "Delegates", });
    internal_static_iotextypes_GenesisDelegate_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_iotextypes_GenesisDelegate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_iotextypes_GenesisDelegate_descriptor,
        new java.lang.String[] { "OperatorAddr", "RewardAddr", "Votes", });
    internal_static_iotextypes_GenesisRewarding_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_iotextypes_GenesisRewarding_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_iotextypes_GenesisRewarding_descriptor,
        new java.lang.String[] { "InitAdminAddr", "InitBalance", "BlockReward", "EpochReward", "NumDelegatesForEpochReward", "FoundationBonus", "NumDelegatesForFoundationBonus", "FoundationBonusLastEpoch", "ProductivityThreshold", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
