// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/types/genesis.proto
// Protobuf Java Version: 4.29.1

package com.github.iotexproject.grpc.types;

/**
 * Protobuf type {@code iotextypes.GenesisRewarding}
 */
public final class GenesisRewarding extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:iotextypes.GenesisRewarding)
    GenesisRewardingOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 1,
      /* suffix= */ "",
      GenesisRewarding.class.getName());
  }
  // Use GenesisRewarding.newBuilder() to construct.
  private GenesisRewarding(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GenesisRewarding() {
    initAdminAddr_ = "";
    initBalance_ = "";
    blockReward_ = "";
    epochReward_ = "";
    foundationBonus_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.iotexproject.grpc.types.GenesisOuterClass.internal_static_iotextypes_GenesisRewarding_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.iotexproject.grpc.types.GenesisOuterClass.internal_static_iotextypes_GenesisRewarding_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.iotexproject.grpc.types.GenesisRewarding.class, com.github.iotexproject.grpc.types.GenesisRewarding.Builder.class);
  }

  public static final int INITADMINADDR_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object initAdminAddr_ = "";
  /**
   * <code>string initAdminAddr = 1;</code>
   * @return The initAdminAddr.
   */
  @java.lang.Override
  public java.lang.String getInitAdminAddr() {
    java.lang.Object ref = initAdminAddr_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      initAdminAddr_ = s;
      return s;
    }
  }
  /**
   * <code>string initAdminAddr = 1;</code>
   * @return The bytes for initAdminAddr.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInitAdminAddrBytes() {
    java.lang.Object ref = initAdminAddr_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      initAdminAddr_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INITBALANCE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object initBalance_ = "";
  /**
   * <code>string initBalance = 2;</code>
   * @return The initBalance.
   */
  @java.lang.Override
  public java.lang.String getInitBalance() {
    java.lang.Object ref = initBalance_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      initBalance_ = s;
      return s;
    }
  }
  /**
   * <code>string initBalance = 2;</code>
   * @return The bytes for initBalance.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInitBalanceBytes() {
    java.lang.Object ref = initBalance_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      initBalance_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BLOCKREWARD_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object blockReward_ = "";
  /**
   * <code>string blockReward = 3;</code>
   * @return The blockReward.
   */
  @java.lang.Override
  public java.lang.String getBlockReward() {
    java.lang.Object ref = blockReward_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      blockReward_ = s;
      return s;
    }
  }
  /**
   * <code>string blockReward = 3;</code>
   * @return The bytes for blockReward.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBlockRewardBytes() {
    java.lang.Object ref = blockReward_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      blockReward_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EPOCHREWARD_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object epochReward_ = "";
  /**
   * <code>string epochReward = 4;</code>
   * @return The epochReward.
   */
  @java.lang.Override
  public java.lang.String getEpochReward() {
    java.lang.Object ref = epochReward_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      epochReward_ = s;
      return s;
    }
  }
  /**
   * <code>string epochReward = 4;</code>
   * @return The bytes for epochReward.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEpochRewardBytes() {
    java.lang.Object ref = epochReward_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      epochReward_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUMDELEGATESFOREPOCHREWARD_FIELD_NUMBER = 5;
  private long numDelegatesForEpochReward_ = 0L;
  /**
   * <code>uint64 numDelegatesForEpochReward = 5;</code>
   * @return The numDelegatesForEpochReward.
   */
  @java.lang.Override
  public long getNumDelegatesForEpochReward() {
    return numDelegatesForEpochReward_;
  }

  public static final int FOUNDATIONBONUS_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object foundationBonus_ = "";
  /**
   * <code>string foundationBonus = 6;</code>
   * @return The foundationBonus.
   */
  @java.lang.Override
  public java.lang.String getFoundationBonus() {
    java.lang.Object ref = foundationBonus_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      foundationBonus_ = s;
      return s;
    }
  }
  /**
   * <code>string foundationBonus = 6;</code>
   * @return The bytes for foundationBonus.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFoundationBonusBytes() {
    java.lang.Object ref = foundationBonus_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      foundationBonus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NUMDELEGATESFORFOUNDATIONBONUS_FIELD_NUMBER = 7;
  private long numDelegatesForFoundationBonus_ = 0L;
  /**
   * <code>uint64 numDelegatesForFoundationBonus = 7;</code>
   * @return The numDelegatesForFoundationBonus.
   */
  @java.lang.Override
  public long getNumDelegatesForFoundationBonus() {
    return numDelegatesForFoundationBonus_;
  }

  public static final int FOUNDATIONBONUSLASTEPOCH_FIELD_NUMBER = 8;
  private long foundationBonusLastEpoch_ = 0L;
  /**
   * <code>uint64 foundationBonusLastEpoch = 8;</code>
   * @return The foundationBonusLastEpoch.
   */
  @java.lang.Override
  public long getFoundationBonusLastEpoch() {
    return foundationBonusLastEpoch_;
  }

  public static final int PRODUCTIVITYTHRESHOLD_FIELD_NUMBER = 9;
  private long productivityThreshold_ = 0L;
  /**
   * <code>uint64 productivityThreshold = 9;</code>
   * @return The productivityThreshold.
   */
  @java.lang.Override
  public long getProductivityThreshold() {
    return productivityThreshold_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(initAdminAddr_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, initAdminAddr_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(initBalance_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, initBalance_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(blockReward_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, blockReward_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(epochReward_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, epochReward_);
    }
    if (numDelegatesForEpochReward_ != 0L) {
      output.writeUInt64(5, numDelegatesForEpochReward_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(foundationBonus_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, foundationBonus_);
    }
    if (numDelegatesForFoundationBonus_ != 0L) {
      output.writeUInt64(7, numDelegatesForFoundationBonus_);
    }
    if (foundationBonusLastEpoch_ != 0L) {
      output.writeUInt64(8, foundationBonusLastEpoch_);
    }
    if (productivityThreshold_ != 0L) {
      output.writeUInt64(9, productivityThreshold_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(initAdminAddr_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, initAdminAddr_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(initBalance_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, initBalance_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(blockReward_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, blockReward_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(epochReward_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, epochReward_);
    }
    if (numDelegatesForEpochReward_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(5, numDelegatesForEpochReward_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(foundationBonus_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, foundationBonus_);
    }
    if (numDelegatesForFoundationBonus_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, numDelegatesForFoundationBonus_);
    }
    if (foundationBonusLastEpoch_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(8, foundationBonusLastEpoch_);
    }
    if (productivityThreshold_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(9, productivityThreshold_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.iotexproject.grpc.types.GenesisRewarding)) {
      return super.equals(obj);
    }
    com.github.iotexproject.grpc.types.GenesisRewarding other = (com.github.iotexproject.grpc.types.GenesisRewarding) obj;

    if (!getInitAdminAddr()
        .equals(other.getInitAdminAddr())) return false;
    if (!getInitBalance()
        .equals(other.getInitBalance())) return false;
    if (!getBlockReward()
        .equals(other.getBlockReward())) return false;
    if (!getEpochReward()
        .equals(other.getEpochReward())) return false;
    if (getNumDelegatesForEpochReward()
        != other.getNumDelegatesForEpochReward()) return false;
    if (!getFoundationBonus()
        .equals(other.getFoundationBonus())) return false;
    if (getNumDelegatesForFoundationBonus()
        != other.getNumDelegatesForFoundationBonus()) return false;
    if (getFoundationBonusLastEpoch()
        != other.getFoundationBonusLastEpoch()) return false;
    if (getProductivityThreshold()
        != other.getProductivityThreshold()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INITADMINADDR_FIELD_NUMBER;
    hash = (53 * hash) + getInitAdminAddr().hashCode();
    hash = (37 * hash) + INITBALANCE_FIELD_NUMBER;
    hash = (53 * hash) + getInitBalance().hashCode();
    hash = (37 * hash) + BLOCKREWARD_FIELD_NUMBER;
    hash = (53 * hash) + getBlockReward().hashCode();
    hash = (37 * hash) + EPOCHREWARD_FIELD_NUMBER;
    hash = (53 * hash) + getEpochReward().hashCode();
    hash = (37 * hash) + NUMDELEGATESFOREPOCHREWARD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNumDelegatesForEpochReward());
    hash = (37 * hash) + FOUNDATIONBONUS_FIELD_NUMBER;
    hash = (53 * hash) + getFoundationBonus().hashCode();
    hash = (37 * hash) + NUMDELEGATESFORFOUNDATIONBONUS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getNumDelegatesForFoundationBonus());
    hash = (37 * hash) + FOUNDATIONBONUSLASTEPOCH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getFoundationBonusLastEpoch());
    hash = (37 * hash) + PRODUCTIVITYTHRESHOLD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getProductivityThreshold());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.iotexproject.grpc.types.GenesisRewarding parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.types.GenesisRewarding parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.GenesisRewarding parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.types.GenesisRewarding parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.GenesisRewarding parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.iotexproject.grpc.types.GenesisRewarding parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.GenesisRewarding parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.types.GenesisRewarding parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.github.iotexproject.grpc.types.GenesisRewarding parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.github.iotexproject.grpc.types.GenesisRewarding parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.iotexproject.grpc.types.GenesisRewarding parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.github.iotexproject.grpc.types.GenesisRewarding parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.iotexproject.grpc.types.GenesisRewarding prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code iotextypes.GenesisRewarding}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:iotextypes.GenesisRewarding)
      com.github.iotexproject.grpc.types.GenesisRewardingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.iotexproject.grpc.types.GenesisOuterClass.internal_static_iotextypes_GenesisRewarding_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.iotexproject.grpc.types.GenesisOuterClass.internal_static_iotextypes_GenesisRewarding_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.iotexproject.grpc.types.GenesisRewarding.class, com.github.iotexproject.grpc.types.GenesisRewarding.Builder.class);
    }

    // Construct using com.github.iotexproject.grpc.types.GenesisRewarding.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      initAdminAddr_ = "";
      initBalance_ = "";
      blockReward_ = "";
      epochReward_ = "";
      numDelegatesForEpochReward_ = 0L;
      foundationBonus_ = "";
      numDelegatesForFoundationBonus_ = 0L;
      foundationBonusLastEpoch_ = 0L;
      productivityThreshold_ = 0L;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.iotexproject.grpc.types.GenesisOuterClass.internal_static_iotextypes_GenesisRewarding_descriptor;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.types.GenesisRewarding getDefaultInstanceForType() {
      return com.github.iotexproject.grpc.types.GenesisRewarding.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.types.GenesisRewarding build() {
      com.github.iotexproject.grpc.types.GenesisRewarding result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.iotexproject.grpc.types.GenesisRewarding buildPartial() {
      com.github.iotexproject.grpc.types.GenesisRewarding result = new com.github.iotexproject.grpc.types.GenesisRewarding(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.github.iotexproject.grpc.types.GenesisRewarding result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.initAdminAddr_ = initAdminAddr_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.initBalance_ = initBalance_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.blockReward_ = blockReward_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.epochReward_ = epochReward_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.numDelegatesForEpochReward_ = numDelegatesForEpochReward_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.foundationBonus_ = foundationBonus_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.numDelegatesForFoundationBonus_ = numDelegatesForFoundationBonus_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.foundationBonusLastEpoch_ = foundationBonusLastEpoch_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.productivityThreshold_ = productivityThreshold_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.iotexproject.grpc.types.GenesisRewarding) {
        return mergeFrom((com.github.iotexproject.grpc.types.GenesisRewarding)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.iotexproject.grpc.types.GenesisRewarding other) {
      if (other == com.github.iotexproject.grpc.types.GenesisRewarding.getDefaultInstance()) return this;
      if (!other.getInitAdminAddr().isEmpty()) {
        initAdminAddr_ = other.initAdminAddr_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getInitBalance().isEmpty()) {
        initBalance_ = other.initBalance_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getBlockReward().isEmpty()) {
        blockReward_ = other.blockReward_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getEpochReward().isEmpty()) {
        epochReward_ = other.epochReward_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getNumDelegatesForEpochReward() != 0L) {
        setNumDelegatesForEpochReward(other.getNumDelegatesForEpochReward());
      }
      if (!other.getFoundationBonus().isEmpty()) {
        foundationBonus_ = other.foundationBonus_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.getNumDelegatesForFoundationBonus() != 0L) {
        setNumDelegatesForFoundationBonus(other.getNumDelegatesForFoundationBonus());
      }
      if (other.getFoundationBonusLastEpoch() != 0L) {
        setFoundationBonusLastEpoch(other.getFoundationBonusLastEpoch());
      }
      if (other.getProductivityThreshold() != 0L) {
        setProductivityThreshold(other.getProductivityThreshold());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              initAdminAddr_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              initBalance_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              blockReward_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              epochReward_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              numDelegatesForEpochReward_ = input.readUInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              foundationBonus_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              numDelegatesForFoundationBonus_ = input.readUInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              foundationBonusLastEpoch_ = input.readUInt64();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              productivityThreshold_ = input.readUInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object initAdminAddr_ = "";
    /**
     * <code>string initAdminAddr = 1;</code>
     * @return The initAdminAddr.
     */
    public java.lang.String getInitAdminAddr() {
      java.lang.Object ref = initAdminAddr_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        initAdminAddr_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string initAdminAddr = 1;</code>
     * @return The bytes for initAdminAddr.
     */
    public com.google.protobuf.ByteString
        getInitAdminAddrBytes() {
      java.lang.Object ref = initAdminAddr_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        initAdminAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string initAdminAddr = 1;</code>
     * @param value The initAdminAddr to set.
     * @return This builder for chaining.
     */
    public Builder setInitAdminAddr(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      initAdminAddr_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string initAdminAddr = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearInitAdminAddr() {
      initAdminAddr_ = getDefaultInstance().getInitAdminAddr();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string initAdminAddr = 1;</code>
     * @param value The bytes for initAdminAddr to set.
     * @return This builder for chaining.
     */
    public Builder setInitAdminAddrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      initAdminAddr_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object initBalance_ = "";
    /**
     * <code>string initBalance = 2;</code>
     * @return The initBalance.
     */
    public java.lang.String getInitBalance() {
      java.lang.Object ref = initBalance_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        initBalance_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string initBalance = 2;</code>
     * @return The bytes for initBalance.
     */
    public com.google.protobuf.ByteString
        getInitBalanceBytes() {
      java.lang.Object ref = initBalance_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        initBalance_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string initBalance = 2;</code>
     * @param value The initBalance to set.
     * @return This builder for chaining.
     */
    public Builder setInitBalance(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      initBalance_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string initBalance = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearInitBalance() {
      initBalance_ = getDefaultInstance().getInitBalance();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string initBalance = 2;</code>
     * @param value The bytes for initBalance to set.
     * @return This builder for chaining.
     */
    public Builder setInitBalanceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      initBalance_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object blockReward_ = "";
    /**
     * <code>string blockReward = 3;</code>
     * @return The blockReward.
     */
    public java.lang.String getBlockReward() {
      java.lang.Object ref = blockReward_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        blockReward_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string blockReward = 3;</code>
     * @return The bytes for blockReward.
     */
    public com.google.protobuf.ByteString
        getBlockRewardBytes() {
      java.lang.Object ref = blockReward_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        blockReward_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string blockReward = 3;</code>
     * @param value The blockReward to set.
     * @return This builder for chaining.
     */
    public Builder setBlockReward(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      blockReward_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string blockReward = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockReward() {
      blockReward_ = getDefaultInstance().getBlockReward();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string blockReward = 3;</code>
     * @param value The bytes for blockReward to set.
     * @return This builder for chaining.
     */
    public Builder setBlockRewardBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      blockReward_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object epochReward_ = "";
    /**
     * <code>string epochReward = 4;</code>
     * @return The epochReward.
     */
    public java.lang.String getEpochReward() {
      java.lang.Object ref = epochReward_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        epochReward_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string epochReward = 4;</code>
     * @return The bytes for epochReward.
     */
    public com.google.protobuf.ByteString
        getEpochRewardBytes() {
      java.lang.Object ref = epochReward_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        epochReward_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string epochReward = 4;</code>
     * @param value The epochReward to set.
     * @return This builder for chaining.
     */
    public Builder setEpochReward(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      epochReward_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string epochReward = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEpochReward() {
      epochReward_ = getDefaultInstance().getEpochReward();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string epochReward = 4;</code>
     * @param value The bytes for epochReward to set.
     * @return This builder for chaining.
     */
    public Builder setEpochRewardBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      epochReward_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private long numDelegatesForEpochReward_ ;
    /**
     * <code>uint64 numDelegatesForEpochReward = 5;</code>
     * @return The numDelegatesForEpochReward.
     */
    @java.lang.Override
    public long getNumDelegatesForEpochReward() {
      return numDelegatesForEpochReward_;
    }
    /**
     * <code>uint64 numDelegatesForEpochReward = 5;</code>
     * @param value The numDelegatesForEpochReward to set.
     * @return This builder for chaining.
     */
    public Builder setNumDelegatesForEpochReward(long value) {

      numDelegatesForEpochReward_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 numDelegatesForEpochReward = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumDelegatesForEpochReward() {
      bitField0_ = (bitField0_ & ~0x00000010);
      numDelegatesForEpochReward_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object foundationBonus_ = "";
    /**
     * <code>string foundationBonus = 6;</code>
     * @return The foundationBonus.
     */
    public java.lang.String getFoundationBonus() {
      java.lang.Object ref = foundationBonus_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        foundationBonus_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string foundationBonus = 6;</code>
     * @return The bytes for foundationBonus.
     */
    public com.google.protobuf.ByteString
        getFoundationBonusBytes() {
      java.lang.Object ref = foundationBonus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        foundationBonus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string foundationBonus = 6;</code>
     * @param value The foundationBonus to set.
     * @return This builder for chaining.
     */
    public Builder setFoundationBonus(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      foundationBonus_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string foundationBonus = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearFoundationBonus() {
      foundationBonus_ = getDefaultInstance().getFoundationBonus();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string foundationBonus = 6;</code>
     * @param value The bytes for foundationBonus to set.
     * @return This builder for chaining.
     */
    public Builder setFoundationBonusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      foundationBonus_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private long numDelegatesForFoundationBonus_ ;
    /**
     * <code>uint64 numDelegatesForFoundationBonus = 7;</code>
     * @return The numDelegatesForFoundationBonus.
     */
    @java.lang.Override
    public long getNumDelegatesForFoundationBonus() {
      return numDelegatesForFoundationBonus_;
    }
    /**
     * <code>uint64 numDelegatesForFoundationBonus = 7;</code>
     * @param value The numDelegatesForFoundationBonus to set.
     * @return This builder for chaining.
     */
    public Builder setNumDelegatesForFoundationBonus(long value) {

      numDelegatesForFoundationBonus_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 numDelegatesForFoundationBonus = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearNumDelegatesForFoundationBonus() {
      bitField0_ = (bitField0_ & ~0x00000040);
      numDelegatesForFoundationBonus_ = 0L;
      onChanged();
      return this;
    }

    private long foundationBonusLastEpoch_ ;
    /**
     * <code>uint64 foundationBonusLastEpoch = 8;</code>
     * @return The foundationBonusLastEpoch.
     */
    @java.lang.Override
    public long getFoundationBonusLastEpoch() {
      return foundationBonusLastEpoch_;
    }
    /**
     * <code>uint64 foundationBonusLastEpoch = 8;</code>
     * @param value The foundationBonusLastEpoch to set.
     * @return This builder for chaining.
     */
    public Builder setFoundationBonusLastEpoch(long value) {

      foundationBonusLastEpoch_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 foundationBonusLastEpoch = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearFoundationBonusLastEpoch() {
      bitField0_ = (bitField0_ & ~0x00000080);
      foundationBonusLastEpoch_ = 0L;
      onChanged();
      return this;
    }

    private long productivityThreshold_ ;
    /**
     * <code>uint64 productivityThreshold = 9;</code>
     * @return The productivityThreshold.
     */
    @java.lang.Override
    public long getProductivityThreshold() {
      return productivityThreshold_;
    }
    /**
     * <code>uint64 productivityThreshold = 9;</code>
     * @param value The productivityThreshold to set.
     * @return This builder for chaining.
     */
    public Builder setProductivityThreshold(long value) {

      productivityThreshold_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 productivityThreshold = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearProductivityThreshold() {
      bitField0_ = (bitField0_ & ~0x00000100);
      productivityThreshold_ = 0L;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:iotextypes.GenesisRewarding)
  }

  // @@protoc_insertion_point(class_scope:iotextypes.GenesisRewarding)
  private static final com.github.iotexproject.grpc.types.GenesisRewarding DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.iotexproject.grpc.types.GenesisRewarding();
  }

  public static com.github.iotexproject.grpc.types.GenesisRewarding getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GenesisRewarding>
      PARSER = new com.google.protobuf.AbstractParser<GenesisRewarding>() {
    @java.lang.Override
    public GenesisRewarding parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GenesisRewarding> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GenesisRewarding> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.iotexproject.grpc.types.GenesisRewarding getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

